import {reviewPoster} from '../lib/commercial-poster/review';
import {test,beforeEach,afterEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {db} from '../lib/database/client';
import {createCampaign,getCampaign} from '../lib/database/campaigns';
import {demoBrief} from '../lib/demo';
import {runCampaign} from '../lib/agents/orchestrator';
import {getProviders} from '../lib/providers';
import {ComfyUIProvider} from '../lib/providers/image/comfyui';
import {storage} from '../lib/storage';
import {getWorkflow} from '../lib/workflows/registry';
import {commercialPosterInputSchema} from '../types/commercial-poster';
import {jobInputSchema} from '../types/jobs';
import {commercialPosterRequest,commercialPosterPlan,requireKleinDependencies} from '../lib/commercial-poster/pipeline';
import {checkCommercialPosterReadiness} from '../lib/commercial-poster/readiness';
import {createJob,getJob,cancelJob,retryJob} from '../lib/jobs/store';
import {workOnce} from '../lib/jobs/executor';
const oldEnv={...process.env},oldFetch=global.fetch,ids:string[]=[],uploads:string[]=[],outputs=new Set<string>();
const env={IMAGE_PROVIDER:'comfyui',COMFYUI_URL:'http://127.0.0.1:8188',COMFYUI_KLEIN_URL:'http://127.0.0.1:8190',COMFYUI_CHECKPOINT_NAME:'legacy.safetensors',COMFYUI_WORKFLOW_MODE:'auto'};
beforeEach(()=>{Object.assign(process.env,{LLM_PROVIDER:'mock',VISION_PROVIDER:'mock',IMAGE_PROVIDER:'mock',MAX_REFINEMENTS:'0'});global.fetch=async()=>{throw new Error('Live network forbidden');};});
afterEach(()=>{process.env={...oldEnv};global.fetch=oldFetch;});
after(async()=>{for(const id of ids){const c=await getCampaign(id);for(const a of c?.assets??[])for(const g of a.generations)if(g.imageUrl.startsWith('/api/generated/'))outputs.add(g.imageUrl.split('/').at(-1)!);}await db.campaign.deleteMany({where:{id:{in:ids}}});for(const id of uploads)await storage.remove(id);for(const f of outputs)await storage.removeGenerated(f);await db.$disconnect();});
async function fixture(){const c=await createCampaign({...demoBrief,name:'TEST-KLEIN-'+randomUUID()});ids.push(c.id);await runCampaign(c.id,()=>{},undefined,getProviders());const id=randomUUID(),bytes=await sharp({create:{width:600,height:400,channels:3,background:'#eeddcc'}}).png().toBuffer();uploads.push(id);await storage.put(id,bytes);await db.upload.create({data:{id,campaignId:c.id,name:'test-product.png',role:'product',mime:'image/png',size:bytes.length}});const campaign=(await getCampaign(c.id))!,asset=campaign.assets.find(a=>a.kind==='hero')!,input=commercialPosterInputSchema.parse({sourceId:id});return {campaign,input,...commercialPosterRequest(campaign,asset.id,input)};}
function catalog(){const w=getWorkflow('commercial_poster_v1','1.0.0'),c:Record<string,{input:{required:Record<string,unknown[]>}}>=Object.fromEntries(w.requiredNodes.map(n=>[n,{input:{required:{}}}]));for(const m of w.requiredModels)c[m.node].input.required[m.input]=[[m.defaultName]];return c;}
async function network(onQueue?:()=>Promise<void>){const c=catalog(),png=await sharp({create:{width:880,height:592,channels:3,background:'#123456'}}).png().toBuffer(),graphs:Record<string,{class_type:string;inputs:Record<string,unknown>}>[]=[];let uploadCount=0;
 global.fetch=async(url,init)=>{const u=String(url);assert.ok(u.startsWith('http://127.0.0.1:8190/'),'Only Klein endpoint may be called');if(u.endsWith('object_info'))return Response.json(c);if(u.endsWith('upload/image')){uploadCount++;const blob=(init?.body as FormData).get('image') as Blob,info=await sharp(Buffer.from(await blob.arrayBuffer())).metadata();assert.equal(info.width,600);assert.equal(info.height,400);return Response.json({name:'product-test.png',subfolder:'',type:'input'});}if(u.endsWith('/prompt')){graphs.push(JSON.parse(String(init?.body)).prompt);await onQueue?.();return Response.json({prompt_id:'test-id'});}if(u.includes('/history/'))return Response.json({'test-id':{status:{completed:true,status_str:'success'},outputs:{'9':{images:[{filename:'output.png',subfolder:'',type:'output'}]}}}});if(u.includes('/view?'))return new Response(new Uint8Array(png));throw new Error('Unexpected request');};return {graphs,uploads:()=>uploadCount};
}
test('pinned registry, faithful four-step graph, prompt adapter and explicit placement contract',async()=>{const f=await fixture(),plan=await commercialPosterPlan(f.request),w=getWorkflow('commercial_poster_v1','1.0.0');assert.equal(w.status,'experimental');assert.equal(w.releaseState,'experimental');assert.deepEqual(w.outputProfiles,{hero:{width:880,height:592}});assert.equal(plan.graph['62'].inputs.steps,4);assert.equal(plan.graph['63'].inputs.cfg,1);assert.equal(plan.graph['66'].inputs.batch_size,1);assert.equal(plan.graph['80'].inputs.megapixels,0.5);assert.match(plan.positive,/negative space/);assert.ok(plan.positive.includes(f.asset.prompt.environment));assert.throws(()=>commercialPosterInputSchema.parse({...f.input,width:1024}));assert.throws(()=>commercialPosterRequest(f.campaign,f.campaign.assets.find(a=>a.kind==='post')!.id,f.input),/Hero/);assert.throws(()=>commercialPosterRequest(f.campaign,f.asset.id,{...f.input,sourceId:'other'}),/belonging/);assert.equal(jobInputSchema.safeParse({campaignId:f.campaign.id,assetId:f.asset.id,commercialPoster:f.input,instruction:'refine this',requestKey:randomUUID()}).success,false);});
test('readiness is read-only and blocks missing nodes, models, configuration and reference',async()=>{const f=await fixture();let calls=0;const fetcher:typeof fetch=async(url,init)=>{assert.equal(init?.method,undefined);assert.ok(String(url).endsWith('object_info'));calls++;return Response.json(catalog());};assert.equal((await checkCommercialPosterReadiness(f.campaign,f.asset.id,f.input,{env,fetch:fetcher})).canGenerate,true);assert.equal(calls,1);for(const key of ['ReferenceLatent','Flux2Scheduler','CLIPLoader']){const c=catalog();delete c[key];assert.throws(()=>requireKleinDependencies(c),/unavailable/);}const c=catalog();c.UNETLoader.input.required.unet_name=[[]];assert.throws(()=>requireKleinDependencies(c),/checkpoint/);assert.equal((await checkCommercialPosterReadiness(f.campaign,f.asset.id,f.input,{env:{...env,COMFYUI_KLEIN_URL:''},fetch:fetcher})).canGenerate,false);assert.equal((await checkCommercialPosterReadiness(f.campaign,f.asset.id,{...f.input,sourceId:'missing'},{env,fetch:fetcher})).canGenerate,false);});
test('durable integration saves immutable version, native references, usage and advanced sampler metadata without paid calls',async()=>{const f=await fixture(),before=JSON.stringify(f.asset.generations),n=await network(),p=getProviders();p.image=new ComfyUIProvider(env);p.llm.generate=async()=>{throw new Error('Paid/text stage forbidden');};p.vision.evaluate=async()=>{throw new Error('Vision forbidden');};Object.assign(process.env,env);const j=await createJob({campaignId:f.campaign.id,assetId:f.asset.id,commercialPoster:f.input,requestKey:randomUUID()});await workOnce({providers:p});assert.equal((await getJob(j.id)).status,'completed');const asset=(await getCampaign(f.campaign.id))!.assets.find(a=>a.id===f.asset.id)!,g=asset.generations.at(-1)!;assert.equal(JSON.stringify(asset.generations.slice(0,-1)),before);assert.equal(g.version,f.asset.generations.at(-1)!.version+1);assert.equal(g.evaluation,null);assert.equal(g.status,'generated');assert.equal(n.graphs.length,1);assert.equal(n.uploads(),1);assert.equal(n.graphs[0]['200'].inputs.image,'product-test.png');const r=g.context!.reproducibility!;assert.equal(r.workflowId,'commercial_poster_v1');assert.equal(r.registeredHashMatches,true);assert.equal(r.seed,f.input.seed);assert.equal(r.sampling[0].steps,4);assert.equal(r.sampling[0].sampler,'euler');assert.equal(r.references[0].strength,null);assert.equal(r.dependencies.models.length,3);const usage=await db.usageEvent.findMany({where:{jobId:j.id}});assert.equal(usage.length,1);assert.equal(usage[0].status,'success');assert.ok(usage[0].durationMs!>=0);assert.equal(JSON.parse(usage[0].metadata).workflow,'commercial_poster_v1');assert.equal(usage[0].generationId,g.id);});
test('in-flight cancellation preserves output and retry does not regenerate or review it',async()=>{const f=await fixture(),j=await createJob({campaignId:f.campaign.id,assetId:f.asset.id,commercialPoster:f.input,requestKey:randomUUID()}),n=await network(async()=>{await cancelJob(j.id);}),p=getProviders();p.image=new ComfyUIProvider(env);Object.assign(process.env,env);await workOnce({providers:p});assert.equal((await getJob(j.id)).status,'cancelled');const before=(await getCampaign(f.campaign.id))!.assets.find(a=>a.id===f.asset.id)!.generations;assert.ok(before.at(-1)!.imageUrl);await retryJob(j.id,1);await workOnce({providers:p});assert.equal((await getJob(j.id)).status,'completed');assert.equal(n.graphs.length,1);assert.equal((await getCampaign(f.campaign.id))!.assets.find(a=>a.id===f.asset.id)!.generations.length,before.length);});
test('legacy auto selection stays legacy and unavailable Klein queues no image',async()=>{const f=await fixture(),provider=new ComfyUIProvider(env);const legacy={...f.request,commercialPoster:undefined,commercialPosterPrompt:undefined};assert.notEqual((await provider.resolveWorkflow(legacy)).mode,'commercial_poster_v1');Object.assign(process.env,env);global.fetch=async(url)=>{assert.ok(String(url).endsWith('object_info'));return Response.json({});};const j=await createJob({campaignId:f.campaign.id,assetId:f.asset.id,commercialPoster:f.input,requestKey:randomUUID()});await workOnce();assert.equal((await getJob(j.id)).failureCode,'preflight_blocked');assert.equal((await getCampaign(f.campaign.id))!.assets.find(a=>a.id===f.asset.id)!.generations.length,f.asset.generations.length);assert.equal(await db.usageEvent.count({where:{jobId:j.id}}),0);});

test('explicit poster review saves once and repeats return the existing evaluation without another call',async()=>{
 const f=await fixture();await network();const output=await new ComfyUIProvider(env).generate(f.request);outputs.add(output.imageUrl.split('/').at(-1)!);
 const context={workflowMode:'commercial_poster_v1',workflowReason:'Offline fixture',previousGenerationId:null,previousVersion:null,refinementIndex:0,targetedCorrections:[],commercialPoster:output.commercialPoster,reproducibility:output.reproducibility};
 const g=await db.generation.create({data:{assetId:f.asset.id,version:99,prompt:JSON.stringify({...f.request.prompt,_generation:context}),imageUrl:output.imageUrl,provider:'comfyui',reason:'Offline review fixture'}});let calls=0;
 const provider={name:'openai',evaluate:async(r:import('../lib/providers/vision/base').VisionRequest)=>{calls++;assert.equal(r.posterReference?.id,f.input.sourceId);return {...f.asset.generations[0].evaluation!,provider:'openai'};}};
 const first=await reviewPoster(f.campaign.id,g.id,provider);assert.equal(first.provider,'openai');await reviewPoster(f.campaign.id,g.id,provider);assert.equal(calls,1);
 await assert.rejects(reviewPoster(f.campaign.id,'missing',provider),/saved Commercial Poster/);assert.equal(calls,1);
});
