import {test,beforeEach,afterEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {readFile} from 'node:fs/promises';
import {productHeroInputSchema,productHeroMetadataSchema,productFidelityReviewSchema} from '../types/product-hero';
import {generationContextSchema} from '../types/refinement';
import {decodeProduct,validateProductMask,productPlacement,compositeProduct} from '../lib/product-hero/composite';
import {generateProductHero,productHeroPlan,productHeroRequest} from '../lib/product-hero/pipeline';
import {productTransport} from '../lib/product-hero/transport';
import {checkProductHeroReadiness} from '../lib/product-hero/readiness';
import {getWorkflow,auditRegistry} from '../lib/workflows/registry';
import {loadFixtures,dryRunBenchmark} from '../lib/workflows/benchmark';
import {storage} from '../lib/storage';
import {createCampaign,getCampaign} from '../lib/database/campaigns';
import {db} from '../lib/database/client';
import {runCampaign} from '../lib/agents/orchestrator';
import {demoBrief} from '../lib/demo';
import {getProviders} from '../lib/providers';
import {ComfyUIProvider} from '../lib/providers/image/comfyui';
import {OpenAIVisionProvider} from '../lib/providers/vision/openai';
import {scoreVision} from '../lib/providers/vision/scoring';
import {visionOutputSchema} from '../types/vision';
import {createJob,getJob,cancelJob,retryJob} from '../lib/jobs/store';
import {workOnce} from '../lib/jobs/executor';
import {usageReport} from '../lib/usage/report';
const originalEnv={...process.env},originalFetch=global.fetch,ids:string[]=[],uploads:string[]=[],files=new Set<string>();
const env={COMFYUI_URL:'http://127.0.0.1:8188',COMFYUI_CHECKPOINT_NAME:'test.safetensors',IMAGE_PROVIDER:'comfyui',VISION_PROVIDER:'openai',VISION_MODEL:'gpt-4.1',OPENAI_API_KEY:'sk-offline-test-only'};
beforeEach(()=>{Object.assign(process.env,{...env,LLM_PROVIDER:'mock',IMAGE_PROVIDER:'mock',VISION_PROVIDER:'mock',MAX_REFINEMENTS:'0'});delete process.env.MAX_JOB_API_COST_USD;delete process.env.MAX_CAMPAIGN_API_COST_USD;global.fetch=async()=>{throw new Error('No live network in automated tests');};});
afterEach(()=>{process.env={...originalEnv};global.fetch=originalFetch;});
function artifacts(value:unknown){const text=JSON.stringify(value);for(const match of text.matchAll(/\/api\/generated\/([a-f0-9-]{36}\.png)/g))files.add(match[1]);}
after(async()=>{for(const id of ids)artifacts(await getCampaign(id));await db.campaign.deleteMany({where:{id:{in:ids}}});for(const f of files)await storage.removeGenerated(f).catch(()=>{});for(const id of uploads)await storage.remove(id);await db.$disconnect();});
async function source(){return sharp({create:{width:256,height:256,channels:3,background:'#dc9263'}}).png().toBuffer();}
async function mask(){const data=Buffer.alloc(256*256);for(let y=48;y<208;y++)data.fill(255,y*256+40,y*256+216);return sharp(data,{raw:{width:256,height:256,channels:1}}).png().toBuffer();}
async function background(){return sharp({create:{width:1024,height:768,channels:3,background:'#17365b'}}).png().toBuffer();}
async function campaign(){const c=await createCampaign({...demoBrief,name:'TEST-PRODUCT-HERO-'+randomUUID()});ids.push(c.id);await runCampaign(c.id,()=>{},undefined,getProviders());const id=randomUUID(),bytes=await source();uploads.push(id);await storage.put(id,bytes);await db.upload.create({data:{id,campaignId:c.id,name:'test-product.png',role:'product',mime:'image/png',size:bytes.length}});const current=(await getCampaign(c.id))!,asset=current.assets.find(a=>a.kind==='hero')!,input=productHeroInputSchema.parse({sourceId:id});return {c:current,input,...productHeroRequest(current,asset.id,input)};}
const clean={status:'clear',severity:'none',observation:'Visible edge.',interpretation:'Coherent.',recommendation:'Keep.'};
const fidelity={level:'high',silhouette:'Visible contour preserved.',structure:'Visible parts present.',colour:'Colours match.',logoText:'Small marks not readable.',lighting:'Plausible grounding.',seams:'No obvious seam.',findings:[]} as const;
const vision={brand_consistency:90,composition:90,visual_hierarchy:90,product_visibility:90,colour_consistency:90,campaign_relevance:90,visual_quality:90,prompt_adherence:90,integrity:{visible_people:0,...Object.fromEntries(['limb_plausibility','duplicated_limbs','leg_arm_anatomy','feet_ankles','hands','body_proportions','pose_plausibility','product_structure','duplicated_product_parts','product_prominence'].map(k=>[k,clean]))},blockingIssues:[],findings:[{observation:'Product visible.',interpretation:'Clear hierarchy.',recommendation:'Keep.'}],productFidelity:fidelity};
async function network(options:{missing?:string;afterBackground?:()=>Promise<void>;visionFail?:boolean;drift?:boolean;segMask?:Buffer}={}){
 const seg=options.segMask??await mask(),bg=await background(),catalog:Record<string,{input:{required:Record<string,unknown[]>}}>=Object.fromEntries(['LoadImage','ImageToMask','MaskToSEGS','SAMLoader','SAMDetectorCombined','MaskToImage','SaveImage','CheckpointLoaderSimple','CLIPTextEncode','EmptyLatentImage','KSampler','VAEDecode'].map(n=>[n,{input:{required:{}}}]));catalog.SAMLoader.input.required.model_name=[['sam_vit_b_01ec64.pth']];catalog.CheckpointLoaderSimple.input.required.ckpt_name=[['test.safetensors']];if(options.missing)delete catalog[options.missing];let prompts=0,visions=0,uploaded=0;const graphs:Record<string,{class_type:string;inputs:Record<string,unknown>}>[]=[];
 global.fetch=async(url,init)=>{const u=String(url);
  if(u.includes('api.openai.com')){visions++;const body=JSON.parse(String(init?.body));assert.equal(body.input[0].content.filter((x:{type:string})=>x.type==='input_image').length,2);assert.doesNotMatch(String(init?.body),/sk-offline-test-only|E:\\/);if(options.visionFail)return Response.json({error:'failed'},{status:401});const productFidelity=options.drift?{...fidelity,level:'low',findings:[{category:'product_missing_part',severity:'high',observation:'Reference heel missing in composite.',recommendation:'Fix segmentation.'}]}:fidelity;return Response.json({status:'completed',model:'gpt-4.1',usage:{input_tokens:100,output_tokens:20,total_tokens:120},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({...vision,productFidelity})}]}]});}
  if(u.endsWith('object_info'))return Response.json(catalog);
  if(u.endsWith('upload/image'))return Response.json({name:'hero-upload-'+(++uploaded)+'.png',subfolder:'',type:'input'});
  if(u.endsWith('/prompt')){prompts++;const graph=JSON.parse(String(init?.body)).prompt;graphs.push(graph);const isSeg=Object.values(graph).some((n:unknown)=>(n as {class_type:string}).class_type==='SAMLoader');if(!isSeg)await options.afterBackground?.();return Response.json({prompt_id:isSeg?'seg':'bg'});}
  if(u.includes('history/')){const id=u.endsWith('/seg')?'seg':'bg';return Response.json({[id]:{status:{status_str:'success',completed:true},outputs:{'9':{images:[{filename:id+'.png',subfolder:'',type:'output'}]}}}});}
  if(u.includes('/view?'))return new Response(new Uint8Array(u.includes('seg.png')?seg:bg));
  throw new Error('Unexpected test network request');
 };return {get prompts(){return prompts;},get visions(){return visions;},graphs,catalog};
}
function providers(){const p=getProviders();p.image=new ComfyUIProvider(env);p.vision=new OpenAIVisionProvider();return p;}
test('rejected SAM mask halts the durable pipeline and records failure diagnostics without background or Vision',async()=>{const f=await campaign(),bad=await sharp({create:{width:256,height:256,channels:3,background:'#000000'}}).png().toBuffer(),n=await network({segMask:bad}),job=await createJob({campaignId:f.c.id,assetId:f.asset.id,productHero:{...f.input,segmentation:'sam'},requestKey:randomUUID()});await workOnce({providers:providers(),preflight});assert.equal((await getJob(job.id)).status,'failed');assert.equal(n.prompts,1);assert.equal(n.visions,0);assert.equal(n.graphs[0]['6'].inputs.mask_hint_use_negative,'False');const g=(await getCampaign(f.c.id))!.assets.find(a=>a.id===f.asset.id)!.generations.at(-1)!;artifacts(g);assert.equal(g.imageUrl,'');assert.equal(g.context?.segmentation?.accepted,false);assert.equal(g.context?.segmentation?.attempts[0].diagnostics?.coverage,0);assert.ok(g.context?.segmentation?.attempts[0].maskUrl);});
const preflight=async()=>({checkedAt:new Date().toISOString(),canGenerate:true,items:[],workflowModes:['product_hero_v1'],provisional:false});
test('Product Hero registers experimental templates and keeps proposed/legacy versions',async()=>{const w=getWorkflow('product_hero_v1','1.0.0');assert.equal(w.status,'experimental');assert.equal(getWorkflow('product_hero_v1','0.1.0-proposed').kind,'placeholder');assert.ok((await auditRegistry()).workflows.every(w=>['match','placeholder'].includes(w.state)));assert.throws(()=>productHeroInputSchema.parse({sourceId:'../secret'}));});
test('source, ownership, missing reference and alpha contracts fail explicitly',async()=>{const f=await campaign();assert.throws(()=>productHeroRequest(f.c,f.asset.id,{...f.input,sourceId:'other'}),/belonging/);await assert.rejects(productHeroPlan({...f.request,productHero:{...f.input,sourceId:'missing'}},env),/required/);await assert.rejects(productHeroPlan({...f.request,productHero:{...f.input,segmentation:'source_alpha'}},env),/entire/);await assert.rejects(decodeProduct(Buffer.from('not an image')));});
test('masks reject empty, full, mismatched and border-clipped products',async()=>{const valid=await validateProductMask(await mask(),256,256);assert.ok(valid.coverage>0);for(const color of ['#000000','#ffffff'])await assert.rejects(validateProductMask(await sharp({create:{width:256,height:256,channels:3,background:color}}).png().toBuffer(),256,256),/empty|entire/);await assert.rejects(validateProductMask(await mask(),512,512),/dimensions/);const raw=Buffer.alloc(256*256);for(let y=0;y<100;y++)raw.fill(255,y*256,y*256+100);await assert.rejects(validateProductMask(await sharp(raw,{raw:{width:256,height:256,channels:1}}).png().toBuffer(),256,256),/boundary/);});
test('placement preserves aspect ratio, safe margins and intentional copy space',()=>{for(const placement of ['center','left','right','lower-center','custom'] as const){const input=productHeroInputSchema.parse({sourceId:'test',placement,position:{x:1,y:0}}),p=productPlacement({width:200,height:100},{width:1024,height:768},input);assert.ok(p.left>=Math.floor(1024*.38));assert.ok(p.left+p.width<=1024*.94+1);assert.ok(p.top>=768*.06-1);assert.ok(Math.abs(p.width/p.height-2)<.02);}});
test('compositor preserves every transformed opaque core pixel and stores bounded alpha edges',async()=>{const s=await decodeProduct(await source()),r=await compositeProduct(s,await mask(),await background(),productHeroInputSchema.parse({sourceId:'test',reflection:true}));assert.equal(r.fidelity.coreChangedPixels,0);assert.equal(r.fidelity.coreMeanAbsoluteError,0);assert.ok(r.fidelity.corePixels>100);assert.equal(r.fidelity.status,'core_preserved_identity_unreviewed');assert.equal((await sharp(r.foreground).metadata()).hasAlpha,true);});
test('readiness blocks missing SAM before uploads, generation or paid review',async()=>{const f=await campaign(),n=await network({missing:'SAMDetectorCombined'}),r=await checkProductHeroReadiness(f.c,f.asset.id,f.input,{env});assert.equal(r.canGenerate,false);assert.match(JSON.stringify(r),/SAMDetectorCombined/);assert.equal(n.prompts,0);assert.equal(n.visions,0);});
test('mocked pipeline sends source only to segmentation, records exact provenance and preservation artifacts',async()=>{const f=await campaign(),n=await network(),stages:string[]=[],r=await generateProductHero({...f.request,onStage:undefined},env,async s=>{stages.push(s);});artifacts(r);assert.equal(n.prompts,2);assert.deepEqual(stages,['Product extraction','Background generation','Compositing / shadow integration']);assert.ok(!Object.values(n.graphs[1]).some(n=>n.class_type==='LoadImage'));assert.match(String(n.graphs[1]['6'].inputs.text),/Empty commercial/);assert.match(String(n.graphs[1]['7'].inputs.text),/extra shoe/);assert.equal(r.reproducibility?.workflowId,'product_hero_v1');assert.equal(r.reproducibility?.seed,f.input.seed);assert.equal(r.reproducibility?.registeredHashMatches,true);assert.equal(r.reproducibility?.templates.length,2);assert.equal(r.productHero?.fidelity.coreChangedPixels,0);assert.equal(r.productHero?.review,undefined);assert.doesNotMatch(JSON.stringify(r),/D:\\|E:\\|sk-offline/);});
test('reference-aware Vision records identity blockers despite beautiful component scores',async()=>{const f=await campaign();await network({drift:true});const r=await generateProductHero(f.request,env);artifacts(r);const evaluation=await new OpenAIVisionProvider().evaluate({...f.request,imageUrl:r.imageUrl,objective:f.c.objective,placement:'hero',iteration:0,productHero:r.productHero});assert.equal(evaluation.productFidelity?.level,'low');assert.ok(evaluation.blockingIssues?.some(b=>b.category==='product_missing_part'));assert.ok(evaluation.overall<=49);assert.equal(productFidelityReviewSchema.safeParse({level:'high'}).success,false);});
test('additional fidelity blockers are retained even when the main critic issue list is full',()=>{const primary=visionOutputSchema.parse({...vision,blockingIssues:Array.from({length:12},(_,i)=>({category:'composition',severity:'medium',observation:'Main issue '+i,interpretation:'Visible issue.',recommendation:'Review.'}))});const result=scoreVision(primary,'test',Array.from({length:12},(_,i)=>({category:'product_missing_part',severity:'high',observation:'Identity issue '+i,interpretation:'Missing source part.',recommendation:'Fix mask.'})));assert.equal(result.blockingIssues?.length,24);assert.ok(result.overall<=49);});
test('job saves a new version, stages, one Vision review and non-overlapping usage; old history stays intact',async()=>{const f=await campaign(),before=await db.generation.findMany({where:{assetId:f.asset.id}}),n=await network(),job=await createJob({campaignId:f.c.id,assetId:f.asset.id,productHero:f.input,requestKey:randomUUID()});await workOnce({providers:providers(),preflight});const j=await getJob(job.id);assert.equal(j.status,'completed',j.failure??'');assert.ok(j.events.some(e=>e.stage==='Product extraction'));assert.ok(j.events.some(e=>e.stage==='Vision Review'));const c=(await getCampaign(f.c.id))!,a=c.assets.find(a=>a.id===f.asset.id)!,g=a.generations.at(-1)!;artifacts(g);assert.equal(a.status,'needs_review');assert.equal(g.version,2);assert.equal(g.context?.productHero?.visionProvider,'openai');assert.equal(g.evaluation?.productFidelity?.level,'high');assert.equal(n.visions,1);assert.equal(n.prompts,2);assert.deepEqual(await db.generation.findMany({where:{id:{in:before.map(g=>g.id)}}}),before);const u=await usageReport({jobId:job.id});assert.equal(u.eventCount,3);assert.deepEqual(u.events.map(e=>e.operation).sort(),['product_hero_background','product_hero_segmentation','vision_review']);assert.equal(u.events.filter(e=>e.provider==='openai').length,1);});
test('Vision retry reuses the completed composite with no repeat segmentation or generation',async()=>{const f=await campaign();await network({visionFail:true});const job=await createJob({campaignId:f.c.id,assetId:f.asset.id,productHero:f.input,requestKey:randomUUID()});await workOnce({providers:providers(),preflight});assert.equal((await getJob(job.id)).status,'failed');const before=(await getCampaign(f.c.id))!.assets.find(a=>a.id===f.asset.id)!.generations.at(-1)!;artifacts(before);assert.ok(before.imageUrl);await retryJob(job.id,1);const n=await network();await workOnce({providers:providers(),preflight});assert.equal((await getJob(job.id)).status,'completed');assert.equal(n.prompts,0);assert.equal(n.visions,1);});
test('cancellation before extraction prevents segmentation, background and Vision',async()=>{const f=await campaign(),n=await network(),job=await createJob({campaignId:f.c.id,assetId:f.asset.id,productHero:f.input,requestKey:randomUUID()}),p=providers(),generate=p.image.generate.bind(p.image);p.image.generate=r=>generate({...r,onStage:async s=>{await r.onStage?.(s);if(s==='Product extraction')await cancelJob(job.id);}});await workOnce({providers:p,preflight});assert.equal((await getJob(job.id)).status,'cancelled');assert.equal(n.prompts,0);assert.equal(n.visions,0);});
test('cancellation after a composite finishes saves its version and retry reviews without re-generation',async()=>{const f=await campaign(),n=await network(),job=await createJob({campaignId:f.c.id,assetId:f.asset.id,productHero:f.input,requestKey:randomUUID()}),p=providers(),generate=p.image.generate.bind(p.image);p.image.generate=async r=>{const result=await generate(r);await cancelJob(job.id);return result;};await workOnce({providers:p,preflight});assert.equal((await getJob(job.id)).status,'cancelled');assert.equal(n.visions,0);const g=(await getCampaign(f.c.id))!.assets.find(a=>a.id===f.asset.id)!.generations.at(-1)!;artifacts(g);assert.ok(g.imageUrl);assert.ok(g.context?.productHero);await retryJob(job.id,1);const second=await network();await workOnce({providers:providers(),preflight});assert.equal((await getJob(job.id)).status,'completed');assert.equal(second.prompts,0);assert.equal(second.visions,1);});
test('valid source alpha skips SAM and still preserves opaque product pixels',async()=>{const f=await campaign(),rgb=await source(),alpha=await sharp(await mask()).greyscale().raw().toBuffer(),rgba=await sharp(rgb).joinChannel(alpha,{raw:{width:256,height:256,channels:1}}).png().toBuffer();await storage.put(f.input.sourceId,rgba);const n=await network({missing:'SAMLoader'}),r=await generateProductHero({...f.request,productHero:{...f.input,segmentation:'source_alpha'}},env);artifacts(r);assert.equal(n.prompts,1);assert.equal(r.productHero?.segmentation.method,'source_alpha');assert.equal(r.reproducibility?.templates.length,1);assert.equal(r.productHero?.fidelity.coreChangedPixels,0);});
test('historical metadata stays valid and benchmark keeps a pinned clean reference without claiming a live result',async()=>{const old={workflowMode:'basic',workflowReason:'old',previousGenerationId:null,previousVersion:null,refinementIndex:0,targetedCorrections:[]};assert.equal(generationContextSchema.parse(old).productHero,undefined);const fixtures=await loadFixtures(),f=fixtures.find(f=>f.id==='B01')!;assert.equal(f.targetWorkflow?.version,'1.0.0');assert.equal(f.references[0].file,'shoes.jpg');assert.equal(f.seeds[0],2026091701);const r=await dryRunBenchmark({...f,expectedWorkflow:f.targetWorkflow!},{env});assert.equal(r.metrics.generation,'not_run');assert.equal(r.metrics.vision,null);assert.equal(productHeroMetadataSchema.safeParse({}).success,false);});
test('transport rejects malformed output instead of arbitrary filesystem access',async()=>{const t=productTransport(env,async url=>Response.json(String(url).endsWith('/prompt')?{prompt_id:'test'}:{test:{status:{completed:true},outputs:{'9':{images:[{filename:'../secret.png',subfolder:'',type:'output'}]}}}}));await assert.rejects(t.run({}),/valid PNG/);const template=JSON.parse(await readFile('comfyui/workflows/product_hero_segmentation_api.json','utf8'));assert.equal(template['6'].inputs.detection_hint,'center-1');});
