import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,unlink,mkdir,writeFile,rmdir} from 'node:fs/promises';
import sharp from 'sharp';
import {storage} from '../lib/storage';
import {productHeroInputSchema,type SegmentationReport} from '../types/product-hero';
import {inspectProductMask} from '../lib/product-hero/mask';
import {segmentationPlan,extractProduct,extractionReadiness,acceptManualMask} from '../lib/product-hero/segmentation';
import {readSegmentationReport,SegmentationError} from '../lib/product-hero/segmentation-store';
const ids:string[]=[],reports:SegmentationReport[]=[];
const noNetwork:typeof fetch=async()=>{throw new Error('Automated tests must never use live networking.');};
const env={COMFYUI_URL:'http://127.0.0.1:8188'};
async function pngMask(rects:number[][]){const raw=Buffer.alloc(256*256);for(const [x,y,w,h] of rects)for(let row=y;row<y+h;row++)raw.fill(255,row*256+x,row*256+x+w);return sharp(raw,{raw:{width:256,height:256,channels:1}}).png().toBuffer();}
async function plan(mode='auto',alpha=false){const id=randomUUID(),raw=Buffer.alloc(256*256*4);ids.push(id);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4,fg=x>=40&&x<216&&y>=48&&y<208;raw[i]=fg?60:245;raw[i+1]=fg?80:245;raw[i+2]=fg?100:245;raw[i+3]=alpha&&!fg?0:255;}await storage.put(id,await sharp(raw,{raw:{width:256,height:256,channels:4}}).png().toBuffer());return segmentationPlan(productHeroInputSchema.parse({sourceId:id,segmentation:mode}));}
async function capture(fn:()=>Promise<{report:SegmentationReport}>){try{const r=await fn();reports.push(r.report);return r;}catch(e){if(e instanceof SegmentationError)reports.push(e.report);throw e;}}
after(async()=>{for(const id of ids)await storage.remove(id);for(const r of reports){for(const url of new Set([r.sourceImageUrl,...r.attempts.map(a=>a.maskUrl)].filter(Boolean))){await storage.removeGenerated(url!.split('/').at(-1)!).catch(()=>{});}await unlink('storage/segmentation/'+r.id+'.json').catch(()=>{});}});
test('automatic extraction prioritizes meaningful alpha without network',async()=>{const p=await plan('auto',true);const r=await capture(()=>extractProduct(p,env,noNetwork));assert.equal(r.report.selectedMethod,'source_alpha');assert.equal(r.report.attempts.length,1);assert.equal(r.report.attempts[0].diagnostics?.componentCount,1);assert.match(await extractionReadiness(p,env,{}),/alpha available/);});
test('clean white-background product uses connected background removal before SAM',async()=>{const p=await plan();const r=await capture(()=>extractProduct(p,env,noNetwork));assert.equal(r.report.selectedMethod,'white_border_v1');assert.equal(r.report.attempts[0].accepted,false);assert.equal(r.report.attempts[1].diagnostics?.largestComponentRatio,1);assert.equal(r.report.userIntervention,false);assert.match(await extractionReadiness(p,env,{}),/background removal available/);});
test('empty and near-full masks fail with structured diagnostics',async()=>{for(const rects of [[],[[1,1,254,254]]]){const r=await inspectProductMask(await pngMask(rects),256,256);assert.equal(r.diagnostics.accepted,false);assert.ok(r.diagnostics.reasons.some(s=>/empty|entire/.test(s)));}});
test('fragmentation fails even when total coverage exceeds the old 1% threshold',async()=>{const rects:number[][]=[];for(let y=20;y<220;y+=20)for(let x=20;x<220;x+=20)rects.push([x,y,5,5]);const r=await inspectProductMask(await pngMask(rects),256,256);assert.ok(r.coverage>.01);assert.equal(r.diagnostics.componentCount,100);assert.equal(r.diagnostics.accepted,false);assert.ok(r.diagnostics.largestComponentRatio<.02);});
test('multiple substantial components fail while tiny detached detail can be retained',async()=>{const pair=await inspectProductMask(await pngMask([[20,40,80,160],[150,40,80,160]]),256,256);assert.equal(pair.diagnostics.accepted,false);const detail=await inspectProductMask(await pngMask([[40,48,176,160],[25,100,5,5]]),256,256);assert.equal(detail.diagnostics.componentCount,2);assert.equal(detail.diagnostics.accepted,true);});
test('small well-connected products are not forced to match a shoe area ratio',async()=>{const r=await inspectProductMask(await pngMask([[80,90,28,28]]),256,256);assert.ok(r.coverage<.02);assert.equal(r.diagnostics.accepted,true);});
test('manual mask needs confirmation, retains its checksum and cannot cross source identities',async()=>{const p=await plan('manual'),r=await acceptManualMask(p.input.sourceId,await pngMask([[40,48,176,160]]));reports.push(r);p.input.manualMaskId=r.id;await assert.rejects(extractionReadiness(p,env,{}),/confirm/);p.input.manualMaskConfirmed=true;assert.match(await extractionReadiness(p,env,{}),/manual mask/);const result=await capture(()=>extractProduct(p,env,noNetwork));assert.equal(result.report.selectedMethod,'manual');assert.equal(result.report.userIntervention,true);assert.equal(result.report.maskSha256,r.maskSha256);const other=await plan('manual');other.input.manualMaskId=r.id;other.input.manualMaskConfirmed=true;await assert.rejects(extractionReadiness(other,env,{}),/different source/);});
test('invalid manual mask is preserved and rejected rather than silently accepted',async()=>{const p=await plan('manual');await assert.rejects(acceptManualMask(p.input.sourceId,await pngMask([])),e=>{assert.ok(e instanceof SegmentationError);reports.push(e.report);assert.equal(e.report.accepted,false);assert.ok(e.report.maskUrl);return true;});});
test('SAM failure preserves diagnostic masks and never issues a second prompt',async()=>{const p=await plan('sam'),catalog=Object.fromEntries(Object.values(p.segmentationGraph).map(n=>[n.class_type,{input:{required:{}}}]));let prompts=0;const bad=await pngMask([[1,1,3,3],[30,30,4,4],[200,200,4,4]]);const fetcher:typeof fetch=async(url)=>{const u=String(url);if(u.endsWith('object_info'))return Response.json(catalog);if(u.endsWith('upload/image'))return Response.json({name:'test.png',subfolder:'',type:'input'});if(u.endsWith('/prompt')){prompts++;return Response.json({prompt_id:'test'});}if(u.includes('/history/'))return Response.json({test:{status:{completed:true},outputs:{'9':{images:[{filename:'mask.png',subfolder:'',type:'output'}]}}}});if(u.includes('/view?'))return new Response(bad);throw new Error('Unexpected request');};await assert.rejects(capture(()=>extractProduct(p,env,fetcher)),e=>e instanceof SegmentationError).catch(e=>{throw e;});assert.equal(prompts,1);const r=reports.at(-1)!;assert.equal(r.attempts[0].diagnostics?.accepted,false);assert.equal((await readSegmentationReport(r.id)).accepted,false);});
test('readiness blocks missing paths and reports guided SAM without inference',async()=>{const p=await plan('sam');await assert.rejects(extractionReadiness(p,env,{}),/No usable automatic/);const catalog=Object.fromEntries(Object.values(p.segmentationGraph).map(n=>[n.class_type,{input:{required:{}}}]));assert.match(await extractionReadiness(p,env,catalog),/guided SAM available/);assert.equal(p.segmentationGraph['6'].inputs.mask_hint_use_negative,'False');const legacy=JSON.parse(await readFile('comfyui/workflows/product_hero_segmentation_api.json','utf8'));assert.equal(legacy['6'].inputs.mask_hint_use_negative,'Outter');});
test('installed RMBG is preferred and recorded; missing weights never trigger a download',async()=>{const p=await plan(),root='storage/test-rembg-'+randomUUID(),model=root+'/models/rembg/RMBG-1.4.pth',catalog=Object.fromEntries(['LoadImage','easy imageRemBg','MaskToImage','SaveImage'].map(n=>[n,{input:{required:{}}}])),configured={...env,COMFYUI_LOCAL_ROOT:root,COMFYUI_PRODUCT_HERO_REMBG:'rmbg14'};let prompts=0;const mask=await pngMask([[40,48,176,160]]);const fetcher:typeof fetch=async(url,init)=>{const u=String(url);if(u.endsWith('object_info'))return Response.json(catalog);if(u.endsWith('upload/image'))return Response.json({name:'test.png',subfolder:'',type:'input'});if(u.endsWith('/prompt')){prompts++;const graph=JSON.parse(String(init?.body)).prompt;assert.equal(graph['2'].class_type,'easy imageRemBg');return Response.json({prompt_id:'rembg'});}if(u.includes('/history/'))return Response.json({rembg:{status:{completed:true},outputs:{'9':{images:[{filename:'mask.png',subfolder:'',type:'output'}]}}}});if(u.includes('/view?'))return new Response(mask);throw new Error('No other network permitted');};
 try{const missing=await capture(()=>extractProduct(p,configured,fetcher));assert.equal(missing.report.selectedMethod,'white_border_v1');assert.match(missing.report.attempts[1].reason??'',/missing/);assert.equal(prompts,0);await mkdir(root+'/models/rembg',{recursive:true});await writeFile(model,Buffer.alloc(1_000_001));assert.match(await extractionReadiness(p,configured,catalog),/installed RMBG/);const r=await capture(()=>extractProduct(p,configured,fetcher));assert.equal(r.report.selectedMethod,'rmbg14');assert.ok(r.report.attempts[1].templateHash);assert.equal(prompts,1);}finally{await unlink(model).catch(()=>{});await rmdir(root+'/models/rembg').catch(()=>{});await rmdir(root+'/models').catch(()=>{});await rmdir(root).catch(()=>{});}
});
