'use client';
import {ProviderReadiness} from './provider-readiness';
import {useState} from 'react';
import type {CampaignView} from '@/types/campaign';
import {jsonFetch,postJson} from '@/lib/client';
import {reviewText} from '@/lib/review-comparison';
import type {BrandRule} from '@/types/brand-intelligence';
export function BrandIntelligencePanel({campaign,onUpdated,generationId}:{generationId?:string;campaign:CampaignView;onUpdated:(c:CampaignView)=>void}){
 const intelligence=campaign.brandIntelligence,draft=intelligence?.draft;
 const [rules,setRules]=useState<BrandRule[]>(draft?.rules||[]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [role,setRole]=useState('guidelines');
 const [sourceIds,setSourceIds]=useState(campaign.uploads.filter(u=>u.role!=='pose').map(u=>u.id));
 async function action(body:unknown){setBusy(true);setError('');setMessage('');try{const c=await jsonFetch<CampaignView>(`/api/campaigns/${campaign.id}/brand`,postJson(body));onUpdated(c);setRules(c.brandIntelligence?.draft?.rules||[]);setMessage('Saved. Existing generation history is preserved.');}catch(e){setError((e as Error).message);const c=await jsonFetch<CampaignView>(`/api/campaigns/${campaign.id}`).catch(()=>null);if(c)onUpdated(c);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);setError('');try{const form=new FormData();form.append(role,file);await jsonFetch(`/api/campaigns/${campaign.id}/uploads`,{method:'POST',body:form});const c=await jsonFetch<CampaignView>(`/api/campaigns/${campaign.id}`);onUpdated(c);setSourceIds(c.uploads.filter(u=>u.role!=='pose').map(u=>u.id));setMessage('Uploaded. Analyse materials to prepare a reviewable draft.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="brand-intelligence"><p>Turn brand materials into reviewable rules. Only approved rules affect generation. Source-image observations describe a reference; inferred advice is optional, not a brand mandate.</p>
 <div className="brand-toolbar"><label>Material type<select value={role} onChange={e=>setRole(e.target.value)} disabled={busy}>{['guidelines','logo','style','reference','product'].map(r=><option key={r}>{r}</option>)}</select></label><label>Add material<input aria-label="Add brand material" type="file" disabled={busy} accept={role==='guidelines'?'.pdf,.png,.jpg,.jpeg,.webp':'.png,.jpg,.jpeg,.webp'} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label></div>
 <p className="muted">Up to 8 files · 5 MB each. PDF: readable text, up to 60 pages / 80,000 characters; no OCR.</p>
 <details><summary>Sources to analyse · {sourceIds.length} selected</summary><p>Uncheck unreadable or irrelevant materials, then retry. Existing uploads and approved rules remain stored.</p>{campaign.uploads.filter(u=>u.role!=='pose').map(u=><label className="brand-check" key={u.id}><input type="checkbox" checked={sourceIds.includes(u.id)} disabled={busy} onChange={e=>setSourceIds(ids=>e.target.checked?[...ids,u.id]:ids.filter(id=>id!==u.id))}/>{reviewText(u.name)} · {u.role}</label>)}</details>
 <div className="brand-actions"><button disabled={busy||!sourceIds.length} onClick={()=>action({action:'analyse',sourceIds})}>{busy?'Working…':'Analyse materials'}</button><button disabled={busy||!intelligence?.approved} onClick={()=>action({action:'check'})}>Check brief conflicts</button><button disabled={busy||!intelligence?.approved||!generationId} onClick={()=>action({action:'evaluate',generationId})}>Review selected image with Vision</button></div>
 <p className="muted">Analysis and Vision review use your configured AI provider. Reviewing an existing image preserves its earlier evaluations and does not generate another image.</p>
 {error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status">{message}</p>}
 <details><summary>Analysis provider readiness</summary><ProviderReadiness campaignId={campaign.id} purpose="brand_analysis"/></details><h3>Brand summary</h3><p>{reviewText(draft?.summary)||'No analysis yet. Analyse materials, review the draft, then approve the rules.'}</p>
 <p>{intelligence?.approved?'Approved '+new Date(intelligence.approved.approvedAt).toLocaleString()+' · '+intelligence.approved.rules.length+' rules':'No approved rules yet'}</p>
 {intelligence?.approved&&<details><summary>Currently approved rules</summary>{intelligence.approved.rules.map(r=><p key={r.id}>{reviewText(r.text)} {intelligence.approved?.overriddenRuleIds.includes(r.id)?'— overridden by user':''}</p>)}</details>}
 {(['source','inferred'] as const).map(origin=><section key={origin}><h3>{origin==='source'?'Source-derived rules & observations':'AI-inferred suggestions'}</h3>{!rules.some(r=>r.origin===origin)&&<p className="muted">None extracted.</p>}{rules.filter(r=>r.origin===origin).map(rule=>{const source=draft?.sources.find(s=>s.id===rule.sourceId);return <article className="brand-rule" key={rule.id}><header><span>{rule.category.replaceAll('_',' ')}</span><button disabled={busy} onClick={()=>setRules(r=>r.filter(x=>x.id!==rule.id))}>Remove</button></header><label>Rule<textarea aria-label={'Rule '+rule.id} rows={2} maxLength={800} value={rule.text} disabled={busy} onChange={e=>setRules(r=>r.map(x=>x.id===rule.id?{...x,text:e.target.value}:x))}/></label>{rule.origin==='source'&&<label className="brand-check"><input type="checkbox" checked={rule.binding} disabled={busy} onChange={e=>setRules(r=>r.map(x=>x.id===rule.id?{...x,binding:e.target.checked}:x))}/>Enforce as a brand rule (otherwise context only)</label>}<label className="brand-check"><input type="checkbox" checked={rule.visuallyEvaluable} disabled={busy} onChange={e=>setRules(r=>r.map(x=>x.id===rule.id?{...x,visuallyEvaluable:e.target.checked}:x))}/>Can be evaluated from image pixels</label><small>{source?.role} · <a href={'/api/uploads/'+encodeURIComponent(rule.sourceId)} target="_blank" rel="noreferrer">{reviewText(source?.name)||rule.sourceId}</a>{rule.page?' · page '+rule.page:''}{rule.edited||rule.text!==rule.originalText?' · User edited':''}</small><details><summary>Evidence & uncertainty</summary><p>{reviewText(rule.evidence)}</p><p>{reviewText(rule.uncertainty)||'No uncertainty recorded; verify against the source.'}</p><p>Original extraction: {reviewText(rule.originalText)}</p></details></article>;})}</section>)}
 {draft&&<button className="primary" disabled={busy||rules.some(r=>!r.text.trim())} onClick={()=>action({action:'approve',rules:rules.map(({id,text,visuallyEvaluable,binding})=>({id,text,visuallyEvaluable,binding}))})}>Approve & save rules</button>}
 <h3>Conflicts</h3><p className="muted">Enforce guideline regenerates strategy on the next run. Override disables this rule for future campaign runs; prior versions retain their original rules.</p>{!intelligence?.conflicts.length&&<p>No recorded conflicts. Use “Check brief conflicts” after approval.</p>}{intelligence?.conflicts.map(f=><article className="brand-rule" key={f.id}><strong>{f.stage} · {f.status.replaceAll('_',' ')}</strong><p>Requested: {reviewText(f.requested)}</p><p>Rule: {reviewText(intelligence.approved?.rules.find(r=>r.id===f.ruleId)?.text)}</p><p>{reviewText(f.explanation)}</p><p>Source: {reviewText(intelligence.approved?.sources.find(s=>s.id===intelligence.approved?.rules.find(r=>r.id===f.ruleId)?.sourceId)?.name)||'Not recorded'}</p><div className="brand-actions"><button disabled={busy} onClick={()=>action({action:'resolve',id:f.id,status:'guideline_enforced'})}>Enforce guideline</button><button disabled={busy} onClick={()=>action({action:'resolve',id:f.id,status:'user_override'})}>Override rule for campaign</button></div></article>)}
 <h3>Sources</h3>{campaign.uploads.filter(s=>s.role!=='pose').map(s=><p key={s.id}>{reviewText(s.name)} · {s.role} · {draft?.sources.find(x=>x.id===s.id)?.provider||'Not analysed'}</p>)}
 </div>;
}
