'use client';
import {useRef,useState} from 'react';
import type {CampaignView,AssetView} from '@/types/campaign';
import {commercialPosterInputSchema,type CommercialPosterInput} from '@/types/commercial-poster';
import {ProviderReadiness} from './provider-readiness';
import {jsonFetch,postJson} from '@/lib/client';
export function CommercialPosterPanel({campaign,asset,onQueued}:{campaign:CampaignView;asset:AssetView;onQueued:()=>void}){
 const products=campaign.uploads.filter(u=>u.role==='product'),[sourceId,setSource]=useState(products[0]?.id??''),[seed,setSeed]=useState(20260919),[prepared,setPrepared]=useState<CommercialPosterInput|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),key=useRef(crypto.randomUUID());
 async function queue(){if(!prepared||busy)return;setBusy(true);setError('');try{await jsonFetch('/api/jobs',postJson({campaignId:campaign.id,assetId:asset.id,commercialPoster:prepared,requestKey:key.current}));onQueued();}catch(e){setError(e instanceof Error?e.message:'Queue failed.');}finally{setBusy(false);}}
 return <section><p>Commercial-poster workflow based on the locally tested Klein 4B Distilled pipeline. Experimental; product details may change.</p><p>Hero only · 880 × 592 · 4 steps · batch 1. Uses your saved creative direction and prompt. Saves a new version and waits for review; no automatic Vision or refinement.</p><label>Primary product reference<select disabled={busy} value={sourceId} onChange={e=>{setSource(e.target.value);setPrepared(null);}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{sourceId&&<img src={'/api/uploads/'+sourceId} alt="Selected product reference" style={{maxWidth:'100%',maxHeight:220,objectFit:'contain'}}/>}<p>This workflow uses only the selected product reference. Style, pose and influence controls from other workflows do not apply.</p><label>Seed<input disabled={busy} type="number" min="0" max="4294967295" value={seed} onChange={e=>{setSeed(Number(e.target.value));setPrepared(null);}}/></label>{error&&<p role="alert">{error}</p>}{prepared?<ProviderReadiness campaignId={campaign.id} assetId={asset.id} commercialPoster={prepared} onContinue={()=>{void queue();}}/>:<button disabled={busy||!products.length} onClick={()=>{const result=commercialPosterInputSchema.safeParse({sourceId,seed});if(!result.success){setError('Select a product and an integer seed from 0 to 4294967295.');return;}key.current=crypto.randomUUID();setError('');setPrepared(result.data);}}>Check Commercial Poster readiness</button>}{busy&&<p>Queuing…</p>}</section>;
}
