'use client';
import {creativeModes,modeDefinition,routeCreative,compatibleWorkflows,creativeWorkflowCatalog} from '@/lib/workflows/creative-modes';
import type {CreativeSelection,RoutingDecision} from '@/types/creative-mode';
export function CreativeModeSelection({value,onChange,references,placement='hero',disabled=false,modeLocked=false}:{modeLocked?:boolean;value:CreativeSelection;onChange:(value:CreativeSelection)=>void;references:{id:string;role:string}[];placement?:RoutingDecision['placement'];disabled?:boolean}){
 const route=routeCreative({selection:value,placement,references}),definition=modeDefinition(value.mode),choices=compatibleWorkflows(placement,references);
 return <section><h3>What are you creating?</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:10}}>{creativeModes.map(mode=><button type="button" key={mode.id} aria-pressed={value.mode===mode.id} disabled={disabled||modeLocked} onClick={()=>onChange({mode:mode.id,...(mode.id==='custom'?{override:{workflowId:choices[0]?.id??'legacy_basic_v1',version:'1.0.0',reason:'Manual workflow selection'}}:{})})} style={{display:'block',textAlign:'left',padding:14,border:value.mode===mode.id?'1px solid #b4a2ff':undefined}}><strong>{mode.name}</strong><p className="small">{mode.description}</p></button>)}</div>
 <p><strong>{definition.name}</strong> · {creativeWorkflowCatalog.find(w=>w.id===route.selected.id)?.displayName??"Select a workflow"} · {route.maturity}</p><p className="small">{definition.evidence} {route.reason}</p><p className="small">Required: {definition.required.join(', ')}. Optional: {definition.optional.join(', ')||'none'}. {value.mode==='commercial_poster'?'Hero 880 × 592 only; other placements are currently unsupported.':''}</p>
 <details open={value.mode==='custom'?true:undefined}><summary>Advanced workflow override</summary><p className="small">Recommended: {route.recommended.id} · Selected: {route.selected.id}</p><label>Compatible workflow<select disabled={disabled} value={value.override?.workflowId??''} onChange={e=>onChange({...value,override:e.target.value?{workflowId:e.target.value,version:'1.0.0',reason:value.override?.reason??'Manual workflow selection'}:undefined})}>{value.mode!=='custom'&&<option value="">Recommended</option>}{choices.map(w=><option value={w.id} key={w.id}>{w.displayName} · {w.releaseState}{w.id===route.recommended.id?' · Recommended':''}</option>)}</select></label>{value.override&&<label>Override reason<input disabled={disabled} minLength={3} maxLength={300} value={value.override.reason} onChange={e=>onChange({...value,override:{...value.override!,reason:e.target.value}})}/></label>}</details>
 {route.warnings.map(w=><p key={w} className="small">{w}</p>)}{route.blockers.map(b=><p key={b} className="warning-text">{b}</p>)}</section>;
}
