'use client';
import {useState,useRef} from 'react';
import type {CampaignView,AssetView} from '@/types/campaign';
import {productHeroInputSchema,type ProductHeroInput,type SegmentationReport} from '@/types/product-hero';
import {ProviderReadiness} from './provider-readiness';
import {jsonFetch,postJson} from '@/lib/client';
export function ProductHeroPanel({campaign,asset,onQueued}:{campaign:CampaignView;asset:AssetView;onQueued:()=>void}){
 const products=campaign.uploads.filter(u=>u.role==='product'),styles=campaign.uploads.filter(u=>['style','reference'].includes(u.role));
 const [input,setInput]=useState<ProductHeroInput>(()=>productHeroInputSchema.parse({sourceId:products[0]?.id??'missing'})),[prepared,setPrepared]=useState<ProductHeroInput|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRef(crypto.randomUUID());
 const change=(value:Partial<ProductHeroInput>)=>{setInput(i=>({...i,...value}));setPrepared(null);};
 const [maskReport,setMaskReport]=useState<SegmentationReport|null>(null);
 async function uploadMask(file:File|undefined){if(!file)return;setBusy(true);setError('');setMaskReport(null);change({manualMaskId:undefined,manualMaskConfirmed:false});try{const body=new FormData();body.append('sourceId',input.sourceId);body.append('mask',file);const response=await fetch('/api/campaigns/'+campaign.id+'/product-mask',{method:'POST',body}),data=await response.json();if(!response.ok){setMaskReport(data.report??null);throw new Error(data.error||'Mask upload failed.');}setMaskReport(data);change({manualMaskId:data.id});}catch(e){setError(e instanceof Error?e.message:'Mask upload failed.');}finally{setBusy(false);}}
 async function queue(){if(!prepared||busy)return;setBusy(true);try{await jsonFetch('/api/jobs',postJson({campaignId:campaign.id,assetId:asset.id,productHero:prepared,requestKey:key.current}));onQueued();}catch(e){setError(e instanceof Error?e.message:'Could not queue Product Hero.');}finally{setBusy(false);}}
 return <section className="repair-panel"><p>{asset.name} · original product foreground over a separately generated background. Experimental; human review required.</p><p>Use one fully visible opaque product with padding. Avoid cropped, transparent or heavily occluded products. A later review compares source and output through the configured Vision provider.</p>
 <label>Product reference<select disabled={busy} value={input.sourceId} onChange={e=>{change({sourceId:e.target.value,manualMaskId:undefined,manualMaskConfirmed:false});setMaskReport(null);}}>{products.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><img src={'/api/uploads/'+input.sourceId} alt="Product source" style={{maxHeight:220,maxWidth:'100%',objectFit:'contain'}}/>
 <label>Extraction<select disabled={busy} value={input.segmentation} onChange={e=>change({segmentation:e.target.value as ProductHeroInput['segmentation']})}><option value="auto">Automatic · alpha, background removal, guided SAM</option><option value="background_removal">Background removal</option><option value="sam">Guided SAM · product bounding region</option><option value="source_alpha">Existing transparent PNG alpha</option><option value="manual">Upload manual mask</option></select></label>
 {input.segmentation==='manual'&&<fieldset><legend>Manual product mask</legend><p>PNG with the same dimensions as the source: white product, black background. Include every product part. Uploading only checks the mask; it does not generate an image.</p><input aria-label="Upload product mask" disabled={busy} type="file" accept="image/png" onChange={e=>{void uploadMask(e.target.files?.[0]);}}/>{maskReport&&<><img src={maskReport.maskUrl} alt="Uploaded product mask" style={{maxWidth:'100%',maxHeight:220}}/><p>{maskReport.attempts[0]?.diagnostics?`${(maskReport.attempts[0].diagnostics.coverage*100).toFixed(2)}% foreground · ${maskReport.attempts[0].diagnostics.componentCount} components`:''} · {maskReport.accepted?'Sanity checks passed':'Rejected'}</p>{maskReport.accepted&&<label><input type="checkbox" checked={input.manualMaskConfirmed} onChange={e=>change({manualMaskConfirmed:e.target.checked})}/>I confirm this mask includes the complete product and excludes the background.</label>}</>}</fieldset>}
 {['auto','sam'].includes(input.segmentation)&&<fieldset><legend>Product region in source (%)</legend><p>Enclose the complete product; the region centre should lie on the product. Adjust this guidance if SAM extraction fails.</p>{(['x','y','width','height'] as const).map(k=><label key={k}>{k}<input type="number" min="0" max="100" step="1" value={Math.round(input.sourceRegion[k]*100)} onChange={e=>change({sourceRegion:{...input.sourceRegion,[k]:Number(e.target.value)/100}})}/></label>)}</fieldset>}
 <label>Placement<select value={input.placement} onChange={e=>change({placement:e.target.value as ProductHeroInput['placement']})}>{['center','left','right','lower-center','custom'].map(v=><option key={v}>{v}</option>)}</select></label>
 {input.placement==='custom'&&(['x','y'] as const).map(k=><label key={k}>Centre {k} (%)<input type="number" min="0" max="100" value={input.position[k]*100} onChange={e=>change({position:{...input.position,[k]:Number(e.target.value)/100}})}/></label>)}
 <label>Product width target (%)<input type="number" min="25" max="80" value={input.scale*100} onChange={e=>change({scale:Number(e.target.value)/100})}/></label><small>Clamped to preserve proportions, safe margins and copy space.</small>
 <label>Copy space<select value={input.copySpace} onChange={e=>change({copySpace:e.target.value as ProductHeroInput['copySpace']})}><option>left</option><option>right</option><option>none</option></select></label>
 <label>Optional style reference<select value={input.styleId??''} onChange={e=>change({styleId:e.target.value||undefined})}><option value="">None</option>{styles.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label>
 <label>Background direction<textarea maxLength={1500} value={input.backgroundDirection} onChange={e=>change({backgroundDirection:e.target.value})}/></label>
 <label>Seed<input type="number" min="0" max="4294967295" value={input.seed} onChange={e=>change({seed:Number(e.target.value)})}/></label>
 <label><input type="checkbox" checked={input.reflection} onChange={e=>change({reflection:e.target.checked})}/>Subtle reflection for a glossy surface</label><p>Preservation: transformed opaque product core remains unchanged. No global relighting, product inpainting or generative upscale.</p>
 {error&&<p role="alert">{error}</p>}{prepared?<ProviderReadiness campaignId={campaign.id} assetId={asset.id} productHero={prepared} onContinue={()=>{void queue();}}/>:<button className="primary" disabled={!products.length||busy} onClick={()=>{const p=productHeroInputSchema.safeParse(input);if(!p.success){setError(p.error.issues.map(i=>i.message).join(' '));return;}setError('');key.current=crypto.randomUUID();setPrepared(p.data);}}>Check Product Hero readiness</button>}{busy&&<p>Queuing…</p>}</section>;
}
