'use client';
import type {ProductHeroInput} from '@/types/product-hero';
import type {RepairRequest} from '@/types/repair';
import {useCallback,useEffect,useRef,useState} from 'react';
import {jsonFetch,postJson} from '@/lib/client';
import type {ReadinessReport} from '@/types/readiness';
import type {ConditioningStrength} from '@/types/reference';
export function ProviderReadiness({campaignId,assetId,repair,productHero,commercialPoster,workflowOverride,refine=false,conditioningStrength,purpose='generation',onContinue}:{workflowOverride?:import('@/types/creative-mode').CreativeSelection['override']|null;commercialPoster?:import('@/types/commercial-poster').CommercialPosterInput;productHero?:ProductHeroInput;repair?:RepairRequest;campaignId?:string;assetId?:string;refine?:boolean;conditioningStrength?:ConditioningStrength;purpose?:'generation'|'brand_analysis';onContinue?:()=>void}){
 const [report,setReport]=useState<ReadinessReport|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const sequence=useRef(0);
 const strengths=JSON.stringify(conditioningStrength),repairJson=JSON.stringify(repair),productJson=JSON.stringify(productHero),posterJson=JSON.stringify(commercialPoster),overrideJson=JSON.stringify(workflowOverride);
 const recheck=useCallback(async()=>{const current=++sequence.current;setLoading(true);setError('');setReport(null);try{const result=await jsonFetch<ReadinessReport>('/api/readiness',postJson({workflowOverride:overrideJson?JSON.parse(overrideJson):undefined,commercialPoster:posterJson?JSON.parse(posterJson):undefined,productHero:productJson?JSON.parse(productJson):undefined,campaignId,assetId,refine,purpose,repair:repairJson?JSON.parse(repairJson):undefined,conditioningStrength:strengths?JSON.parse(strengths):undefined}));if(current===sequence.current)setReport(result);}catch{if(current===sequence.current)setError('Readiness check failed. Recheck before starting.');}finally{if(current===sequence.current)setLoading(false);}},[campaignId,assetId,refine,purpose,strengths,repairJson,productJson,posterJson,overrideJson]);
 const invalidate=useCallback(()=>{sequence.current++;},[]);
 useEffect(()=>{void recheck();return invalidate;},[recheck,invalidate]);
 return <section className="provider-readiness"><header><h3>Provider readiness</h3><button disabled={loading} onClick={recheck}>{loading?'Checking…':'Recheck'}</button></header><p>Read-only checks. No image generation or paid OpenAI request. Configured means credentials and model settings are present; authentication is not verified.</p>{error&&<p role="alert" className="error-message">{error}</p>}{report&&<><strong className={report.canGenerate?'success-text':'warning-text'}>{report.canGenerate?purpose==='brand_analysis'?'Ready for analysis · see configuration limits':'Ready to generate · see configuration limits':'Cannot start — fix blocking items'}</strong>{report.workflowModes.length>0&&<p>Workflow: {report.workflowModes.join(' / ')}{report.provisional?' · provisional candidates':''}</p>}<div className="readiness-items">{report.items.map(item=><details key={item.id} open={item.severity==='blocking'?true:undefined} className={'readiness-item '+item.severity}><summary><strong>{item.name}</strong><span>{item.status.replaceAll('_',' ')}</span></summary><p>{item.explanation}</p>{item.severity==='blocking'&&<b>Blocking</b>}{item.remediation&&item.status!=='ready'&&<p className="muted">{item.remediation}</p>}</details>)}</div><small>Checked {new Date(report.checkedAt).toLocaleTimeString()}. Recheck refreshes services and installed models. Changes to the server environment file require restarting the server.</small></>}{onContinue&&<button className="primary" disabled={loading||!report?.canGenerate} onClick={onContinue}>Continue to generation</button>}</section>;
}
