'use client';
import type {GenerationView} from '@/types/campaign';
import type {SegmentationReport} from '@/types/product-hero';
function SegmentationDiagnostics({report}:{report:SegmentationReport|undefined}){return report?<section><h4>Product extraction</h4><p>{report.accepted?'Accepted':'Rejected'} · {report.selectedMethod??'No usable method'} · user intervention {report.userIntervention?'yes':'no'}</p>{report.attempts.map((a,i)=><div key={i}><p>{a.method}: {a.accepted?'accepted':'rejected'}{a.diagnostics&&` · coverage ${(a.diagnostics.coverage*100).toFixed(2)}% · ${a.diagnostics.componentCount} components · largest ${(a.diagnostics.largestComponentRatio*100).toFixed(2)}%`}</p>{a.reason&&<p>{a.reason}</p>}{a.maskUrl&&<a href={a.maskUrl} target="_blank" rel="noreferrer">Inspect preserved mask</a>}<p style={{overflowWrap:'anywhere'}}>Mask SHA256: {a.maskSha256??'No mask produced'}</p></div>)}</section>:null;}
export function ReproducibilityPanel({generation}:{generation:GenerationView}){
 const r=generation.context?.reproducibility,hero=generation.context?.productHero;
 const value=(v:unknown)=>v===null||v===undefined?'Not recorded':String(v);
 return <details className="refinement-timeline"><summary>Reproducibility</summary> <p>Creative Mode: {generation.context?.routing?.creativeMode??'Not recorded'}</p>{generation.context?.routing&&<p>Recommended: {generation.context.routing.recommended.id} · Actual: {r?.workflowId??generation.context?.workflowMode??'Not recorded'} · Routing: {generation.context.routing.reason} · {generation.context.routing.maturity}</p>}<SegmentationDiagnostics report={generation.context?.segmentation??hero?.segmentation.report}/>{!r?<p>Not recorded. Historical workflow labels do not establish the registry version, template hash, checkpoint or seed.</p>:<>
<dl className="stored-prompt"><div><dt>Workflow</dt><dd>{r.workflowId} · {r.workflowVersion}</dd></div><div><dt>Template hash</dt><dd style={{overflowWrap:'anywhere'}}>{r.templateHash}</dd></div><div><dt>Definition hash (including extensions)</dt><dd style={{overflowWrap:'anywhere'}}>{r.definitionHash}</dd></div><div><dt>Registry match</dt><dd>{r.registeredHashMatches?'Matches pinned template bundle':'Changed template — not the pinned release'}</dd></div><div><dt>Checkpoint / seed</dt><dd>{value(r.checkpoint)} / {value(r.seed)}</dd></div><div><dt>Resolution</dt><dd>{r.resolution.width} × {r.resolution.height}</dd></div></dl>
 {r.sampling.map(s=><p key={s.nodeId}>{s.stage}: {value(s.sampler)} / {value(s.scheduler)} · steps {value(s.steps)} · CFG {value(s.cfg)} · denoise {value(s.denoise)} · seed {value(s.seed)}</p>)}
 {generation.context?.commercialPoster&&<section><h4>Experimental Klein poster</h4><p>Duration {generation.context.commercialPoster.durationMs} ms · prompt adapter {generation.context.commercialPoster.promptAdapter} · Vision not requested automatically.</p><details><summary>Submitted creative prompt</summary><pre style={{whiteSpace:'pre-wrap'}}>{generation.context.commercialPoster.positivePrompt}</pre></details></section>}
 <p>ControlNet: {r.controlNet.length?r.controlNet.map(c=>`${value(c.model)} / ${value(c.preprocessor)} / strength ${value(c.strength)}, ${value(c.start)}–${value(c.end)}`).join('; '):'None used'}</p>
 <p>Reference conditioning: {r.references.length?r.references.map(x=>`${x.role} / ${x.id} / ${x.weightType} / strength ${x.strength===null?'not configurable':x.strength}`).join('; '):'None used'}</p>
 <p>Detailer: {r.detailer.enabled?value(r.detailer.detector)+' · '+JSON.stringify(r.detailer.parameters):'Disabled / not used'}</p>
 <p>ComfyUI version: {value(r.dependencies.comfyuiVersion)}</p><p>Runtime: {r.dependencies.runtime.node} · {r.dependencies.runtime.platform} / {r.dependencies.runtime.arch}</p>
 <details><summary>Dependency snapshot</summary>{r.dependencies.nodes.map(n=><p key={n.classType}>{n.classType} · module {value(n.module)} · version {value(n.version)}</p>)}{r.dependencies.models.map((m,i)=><p key={i}>{m.role}: {value(m.name)}</p>)}</details>
 {hero&&<section><h4>Product Hero preservation</h4><p>Source {hero.input.sourceId} · {hero.segmentation.method} · {hero.segmentation.model??'source alpha'}</p><p>{hero.contract} · {hero.fidelity.corePixels} core pixels checked; {hero.fidelity.coreChangedPixels} changed. Identity: {hero.review?.level??'not reviewed'}.</p><p>Placement {hero.input.placement}: {hero.placement.left}, {hero.placement.top} · {hero.placement.width} × {hero.placement.height}; scale {hero.input.scale}.</p><p>Shadow: {hero.shadow}; reflection {hero.reflection?'enabled':'disabled'}. Integration: {hero.integration}. Inpaint: {hero.inpaint}. Upscale: {hero.upscale}.</p><p>Vision: {hero.visionProvider}. Segmentation {hero.durationsMs.segmentation} ms · background {hero.durationsMs.background} ms · compositing {hero.durationsMs.compositing} ms.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[ ['Source',hero.sourceImageUrl],['Mask',hero.maskUrl],['Foreground',hero.foregroundUrl],['Background',hero.backgroundUrl] ].map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer"><img src={url} alt={label} style={{width:100,height:90,objectFit:'contain'}}/>{label}</a>)}</div>{hero.review&&<><p>Silhouette: {hero.review.silhouette}</p><p>Structure: {hero.review.structure}</p><p>Colour: {hero.review.colour}</p><p>Logo/text: {hero.review.logoText}</p><p>Lighting: {hero.review.lighting}</p><p>Seams: {hero.review.seams}</p>{hero.review.findings.map((f,i)=><p key={i}>{f.category} ({f.severity}): {f.observation}</p>)}</>}<p>{hero.fidelity.limitations.join(' ')}</p></section>}
 <p>Environment differences may change pixels. Model file hashes and undiscoverable dependency versions are not recorded.</p></>}</details>;
}
