'use client';
import {useEffect,useState} from 'react';
import {jsonFetch} from '@/lib/client';
import type {UsageReport,UsageTotals} from '@/types/usage';
const money=(n:number|null)=>n===null?'Unavailable':'Estimated $'+n.toFixed(5);
const tokens=(n:number|null)=>n===null?'unavailable':n.toLocaleString();
function Totals({t}:{t:UsageTotals}){
 return <p>{t.calls} calls · {t.failed} failed{t.pending?` · ${t.pending} pending / outcome unknown`:''}<br/>API: {money(t.apiCostUsd)}{t.unpricedApiCalls?` (partial: ${t.unpricedApiCalls} calls unpriced)`:''} · {tokens(t.inputTokens)} input / {tokens(t.outputTokens)} output tokens · {tokens(t.cachedTokens)} cached (included in input)<br/>{t.localCalls>0&&<>Local GPU: {t.localCompleted}/{t.localCalls} generations completed · {(t.localDurationMs/1000).toFixed(1)}s provider duration · {t.localCostUsd===null?'not monetized':money(t.localCostUsd)}{t.localCostUsd!==null&&t.unpricedLocalCalls>0?' (partial)':''}<br/></>}{t.refinementCalls} prompt refinements · {t.mockCalls} mock calls ($0)</p>;
}
export function UsagePanel({campaignId,jobId,attempt,assetId,generationId,title='Usage',expanded=false,refreshToken}:{campaignId?:string;jobId?:string;attempt?:number;assetId?:string;generationId?:string;title?:string;expanded?:boolean;refreshToken?:string|number}){
 const [open,setOpen]=useState(expanded),[report,setReport]=useState<UsageReport|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const params=new URLSearchParams();for(const [key,value] of Object.entries({campaignId,jobId,attempt,assetId,generationId}))if(value!==undefined)params.set(key,String(value));
 const url='/api/usage?'+params.toString();
 useEffect(()=>{if(!open)return;let active=true;setReport(null);void jsonFetch<UsageReport>(url).then(r=>{if(active){setReport(r);setError('');}}).catch(()=>{if(active)setError('Usage could not be loaded.');});return()=>{active=false;};},[url,open,refresh,refreshToken]);
 return <details className="usage-panel" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{title}</summary>{open&&<div><div className="job-actions"><button onClick={()=>setRefresh(n=>n+1)}>Refresh usage</button><a href={url+'&export=json'} download>Export JSON</a></div>{error&&<p role="alert">{error}</p>}{!report&&!error&&<p>Loading usage…</p>}{report&&(report.eventCount===0?<p>Not recorded</p>:<><Totals t={report.totals}/><p className="small muted">Recorded calls only. Estimated costs are not billing totals. Missing tokens remain unavailable; token sums include reported counts only. Local duration includes upload, queue, generation and retrieval.</p>{report.olderHistoryUnrecorded&&<p>Earlier versions: Not recorded.</p>}<details><summary>Creative Mode / workflow</summary>{report.routingGroups?.map(g=><div key={g.creativeMode+g.workflowId}><strong>{g.creativeMode} · {g.workflowId}</strong><Totals t={g.totals}/></div>)}</details><details><summary>Provider / model breakdown</summary>{report.groups.map(g=><div key={[g.provider,g.category,g.model].join(':')}><strong>{g.provider==='mock'?'Mock':g.provider==='comfyui'?'Local GPU':'Real API'} · {g.category} · {g.model??g.provider}</strong><Totals t={g.totals}/></div>)}</details><details><summary>Recent calls ({Math.min(report.eventCount,100)} of {report.eventCount})</summary>{report.events.map(e=><article key={e.id}><strong>{e.operation} · {e.status}</strong><p>{new Date(e.createdAt).toLocaleString()} · {e.provider} / {e.model??'mock'}{e.attempt?` · attempt ${e.attempt}`:''}<br/>{tokens(e.inputTokens)} input / {tokens(e.outputTokens)} output / {tokens(e.cachedTokens)} cached tokens · {e.provider==='mock'?'Mock $0':e.provider==='comfyui'&&e.estimatedCostUsd===null?'Local GPU / not monetized':money(e.estimatedCostUsd)} · {e.durationMs===null?'duration unavailable':(e.durationMs/1000).toFixed(1)+'s'}</p>{e.provider==='comfyui'&&<pre className="small">{e.metadata}</pre>}<details><summary>Pricing snapshot & associations</summary><pre className="small">{JSON.stringify({campaign:e.campaignId,job:e.jobId,attempt:e.attempt,asset:e.assetId,generation:e.generationId,refinementIndex:e.refinementIndex,pricing:e.pricingSnapshot?JSON.parse(e.pricingSnapshot):'Unavailable'},null,2)}</pre></details></article>)}</details></>)}</div>}</details>;
}
