'use client';
import {RepairDetails} from './repair-details';
import {BrandCompliance} from './brand-compliance';
import {useState} from 'react';
import type {AssetView,CampaignView,GenerationView} from '@/types/campaign';
import {blockerChanges,promptChanges,scoreRows,scoreChange,visionLabel,imageLabel,reviewText} from '@/lib/review-comparison';
import {BlockingIssues,GenerationMetadata,ReviewImage,StopReason,StoredPrompt,VisionFindings} from './generation-review';
export function VersionComparison({asset,campaign,onInspect}:{asset:AssetView;campaign:CampaignView;onInspect:(version:number)=>void}){
 const versions=asset.generations;
 const [aId,setA]=useState(versions.at(-1)?.context?.repair?.request.sourceGenerationId || versions.at(-2)?.id || versions[0]?.id),[bId,setB]=useState(versions.at(-1)?.id);
 const a=versions.find(v=>v.id===aId),b=versions.find(v=>v.id===bId);
 if(!a||!b)return <p className="review-empty">Two saved versions are needed for comparison.</p>;
 const repairPair=b.context?.repair?.request.sourceGenerationId===a.id;
 const blockers=blockerChanges(a.evaluation,b.evaluation),changes=promptChanges(a.prompt,b.prompt);
 const differentReviewers=a.evaluation&&b.evaluation&&(a.evaluation.provider!==b.evaluation.provider||a.evaluation.model!==b.evaluation.model||a.evaluation.scoring?.policy!==b.evaluation.scoring?.policy);
 function side(g:GenerationView,label:string){return <article className="comparison-version" aria-label={label+' version '+g.version}><header><span className="ab-label">{label}</span><h3>Version {g.version}</h3><strong>{g.evaluation?g.evaluation.overall+'/100':'Not evaluated'}</strong></header><p>Creative Mode: {g.context?.routing?.creativeMode??'Not recorded'} · {g.context?.routing?.reason??'Routing not recorded'}</p><p className="review-provenance">{reviewText(g.context?.workflowMode) || 'Workflow not recorded'} · {imageLabel(g)} · {visionLabel(g.evaluation)}</p><ReviewImage key={g.id} generation={g}/><p><time dateTime={g.createdAt}>{new Date(g.createdAt).toLocaleString()}</time> · {g.status || 'Status not recorded'}</p><StopReason generation={g}/><BlockingIssues evaluation={g.evaluation}/><BrandCompliance evaluation={g.evaluation}/><details><summary>Workflow, providers & references</summary><GenerationMetadata generation={g} campaign={campaign}/></details><details><summary>Generation prompt & negative constraints</summary><StoredPrompt generation={g}/></details><details><summary>Why this version?</summary><p>{reviewText(g.reason)||'Reason not recorded'}</p><p>{g.context?.previousVersion?'Based on V'+g.context.previousVersion:'Parent version not recorded'}</p>{g.context?.targetedCorrections.map((c,i)=><p key={i}>{reviewText(c)}</p>)}</details><details><summary>Vision findings</summary><VisionFindings evaluation={g.evaluation}/></details><button className="text-button" onClick={()=>onInspect(g.version)}>Inspect V{g.version} in canvas</button></article>;}
 return <div className="version-comparison"><p className="muted">{asset.name} · Compare saved evidence. No new AI evaluation is performed.</p>{(a.context?.routing?.creativeMode!==b.context?.routing?.creativeMode||a.context?.workflowMode!==b.context?.workflowMode)&&<p className="review-caution">These versions used different workflows or Creative Modes; this is not a matched workflow comparison.</p>}<div className="comparison-selectors">{([{label:'A',id:a.id,set:setA,other:b.id},{label:'B',id:b.id,set:setB,other:a.id}]).map(s=><label key={s.label}>{s.label} · Version<select aria-label={'Version '+s.label} value={s.id} onChange={e=>s.set(e.target.value)}>{versions.map(g=><option value={g.id} key={g.id} disabled={g.id===s.other}>V{g.version} · {g.context?.workflowMode || g.provider} · {g.evaluation?g.evaluation.overall+' / '+visionLabel(g.evaluation):'Not evaluated'}</option>)}</select></label>)}<button aria-label="Swap comparison versions" onClick={()=>{setA(b.id);setB(a.id);}}>Swap A/B</button></div>
 <RepairDetails generation={b} source={versions.find(v=>v.id===b.context?.repair?.request.sourceGenerationId)}/><div className="comparison-pair">{side(a,repairPair?'Before':'A')}{side(b,repairPair?'After':'B')}</div>
 <section className="comparison-section"><div className="section-label">SCORE CHANGES <span>{scoreChange(a.evaluation,b.evaluation)}</span></div><p>Δ = B − A. Labels describe saved numbers, not a winner.</p>{differentReviewers&&<p className="review-caution">These reviews use different providers, models or scoring policies. Numeric differences are not evidence of generation improvement.</p>}{(a.evaluation?.provider==='mock'||b.evaluation?.provider==='mock')&&<p className="review-caution">Mock Vision scores are simulated; they do not measure image quality.</p>}<table className="score-comparison"><thead><tr><th>Dimension</th><th>A · V{a.version}</th><th>B · V{b.version}</th><th>Δ</th></tr></thead><tbody>{scoreRows(a.evaluation,b.evaluation).map(row=><tr key={row.key}><th scope="row">{row.label}</th><td>{row.left??'—'}</td><td>{row.right??'—'}</td><td className={row.delta===null?'':row.delta>0?'delta-up':row.delta<0?'delta-down':''}>{row.delta===null?'—':row.delta>0?'+'+row.delta:row.delta}</td></tr>)}</tbody></table><div className="scoring-explanation">{[a,b].map(g=><p key={g.id}>V{g.version}: {g.evaluation?.scoring?'component mean '+g.evaluation.scoring.componentMean+' · penalty '+(g.evaluation.scoring.penalty??'not recorded')+' · cap '+g.evaluation.scoring.cap:'Score breakdown not recorded.'}</p>)}</div></section>
 <section className="comparison-section"><h3>Blocker changes · A → B</h3><p>Compared by stored category, not inferred issue identity. “Resolved” means no longer reported in B; it does not verify a visual fix.</p>{blockers?<div className="blocker-changes">{[['Resolved',blockers.resolved],['New',blockers.added],['Persistent',blockers.persistent]].map(([label,categories])=><div key={label as string}><h4>{label}</h4><p>{(categories as string[]).length?(categories as string[]).map(c=>c.replaceAll('_',' ')).join(', '):'None'}</p></div>)}</div>:<p>Cannot compare blockers: one review has no recorded blocker details.</p>}</section>
 <section className="comparison-section"><h3>Prompt changes · V{a.version} → V{b.version}</h3><p><span className="diff-added">Added in B</span> · <span className="diff-removed">Removed from A</span>. This compares the selected saved prompts; it does not imply an automatic refinement relationship.</p>{!changes.length?<p>No saved prompt or negative-constraint changes.</p>:changes.map(f=><div className="prompt-change" key={f.key}><h4>{f.key==='negative_prompt'?'Negative constraints':f.key.replaceAll('_',' ')}</h4><p>{f.parts.map((part,i)=>part.kind==='added'?<ins key={i}>{part.text}</ins>:part.kind==='removed'?<del key={i}>{part.text}</del>:<span key={i}>{part.text}</span>)}</p></div>)}</section>
 </div>;
}
