'use client';
import {WorkflowCatalog} from './workflow-catalog';
import {CreativeModeSelection} from './creative-mode-selection';
import type {CreativeSelection} from '@/types/creative-mode';
import {modeDefinition} from '@/lib/workflows/creative-modes';
import {CommercialPosterPanel} from './commercial-poster-panel';
import {ProductHeroPanel} from './product-hero-panel';
import {RepairPanel} from './repair-panel';
import {UsagePanel} from './usage-panel';
import {JobStatus} from './job-status';
import {activeJobStates,type JobView} from '@/types/jobs';
import {ProviderReadiness} from './provider-readiness';
import {BrandIntelligencePanel} from './brand-intelligence';
import {VersionComparison} from './version-comparison';
import {RefinementTimeline} from './refinement-timeline';
import {StopReason} from './generation-review';
import {visionLabel,reviewText} from '@/lib/review-comparison';

import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Zap, Plus, ChevronDown, ArrowUpRight, Layers, Sparkles, Download, Check, RotateCcw, GitCompareArrows, Image as ImageIcon, LayoutGrid, Settings2, FileText, LoaderCircle, X, CircleHelp, Maximize2 } from 'lucide-react';
import { jsonFetch, postJson } from '@/lib/client';
import type { CampaignView, CampaignSummary, GenerationView } from '@/types/campaign';
import { CreateCampaign } from './create-campaign';
import { Dialog } from './dialog';
import { Inspector } from './inspector';
import { Workflow } from '@/components/workflow/workflow';

type Config = { llm: string; image: string; vision: string; threshold: number; max: number };
type Modal = 'review-poster' | 'commercial-poster' | 'product-hero' | 'repair' | 'readiness' | 'brand' | 'create' | 'activity' | 'compare' | 'refine' | 'brief' | 'settings' | 'preview' | null;

export function Workspace() {
  const [campaigns, setCampaigns] = useState<CampaignSummary[]>([]), [campaign, setCampaign] = useState<CampaignView | null>(null);
  const [selected, setSelected] = useState(''), [version, setVersion] = useState<number | null>(null);
  const [modal, setModal] = useState<Modal>(null), [library, setLibrary] = useState(false);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [conditioningStrength,setConditioningStrength]=useState({product:0.8,style:0.4});
  const [instruction, setInstruction] = useState('');
  const [config, setConfig] = useState<Config>({ llm: 'mock', image: 'mock', vision: 'mock', threshold: 80, max: 2 });
  const refreshList = useCallback(async () => { const list = await jsonFetch<CampaignSummary[]>('/api/campaigns'); setCampaigns(list); return list; }, []);
  const load = useCallback(async (id: string) => { const c = await jsonFetch<CampaignView>(`/api/campaigns/${id}`); setCampaign(c); try{localStorage.setItem('creativeflow-campaign',id);}catch{} return c; }, []);
  useEffect(() => { let active = true;
    (async () => { try { const [list, configuration] = await Promise.all([jsonFetch<CampaignSummary[]>('/api/campaigns'), jsonFetch<Config>('/api/config')]); if (!active) return; setCampaigns(list); setConfig(configuration); let saved='';try{saved=localStorage.getItem('creativeflow-campaign')||'';}catch{} const current=list.find(c=>c.id===saved)||list[0]; if (current) { const c = await jsonFetch<CampaignView>(`/api/campaigns/${current.id}`); if (active) setCampaign(c); } } catch (e) { if (active) setError(e instanceof Error ? e.message : 'Could not load workspace.'); } finally { if (active) setLoading(false); } })();
    return () => { active = false; };
  }, []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); }, [notice]);
  const [jobs,setJobs]=useState<JobView[]>([]),[jobRefresh,setJobRefresh]=useState(0);
  const [runSelection,setRunSelection]=useState<CreativeSelection|undefined>();
  const submission=useRef(false);
  const asset = campaign?.assets.find(a => a.id === selected) ?? campaign?.assets[0];
  const generation = asset?.generations.find(g => g.version === version) ?? asset?.generations.at(-1);
  const latest = asset?.generations.at(-1);
  const running = busy || jobs.some(j=>j.campaignId===campaign?.id&&activeJobStates.includes(j.status)) || campaign?.status === 'running';
  const reviews=campaign?.assets.flatMap(a=>a.generations.at(-1)?.evaluation?[a.generations.at(-1)!.evaluation!]:[]) || [];
  const reviewProviders=new Set(reviews.map(r=>r.provider));
  const averageLabel=!reviews.length?'Awaiting evaluation':reviewProviders.size>1?'Mixed-source reviews':Math.round(reviews.reduce((n,e)=>n+e.overall,0)/reviews.length)+'/100 · '+visionLabel(reviews[0])+' average';
  async function openCampaign(id: string) { setLoading(true); setJobs([]); setError(''); setSelected(''); setVersion(null); setLibrary(false); try { await load(id); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  const [pendingRun,setPendingRun]=useState<{id:string;assetId?:string;refine?:string;requestKey:string}|null>(null);
  async function run(id:string,assetId?:string,refine?:string){setRunSelection(campaign?.creative);setPendingRun({id,assetId,refine,requestKey:crypto.randomUUID()});setModal('readiness');}
  async function executeRun(id: string, assetId?: string, refine?: string) {
    if(submission.current)return;submission.current=true;setBusy(true);setError('');setVersion(null);
    try {
      const job=await jsonFetch<JobView>('/api/jobs',postJson({workflowOverride:runSelection?.override??null,campaignId:id,assetId,instruction:refine,conditioningStrength,requestKey:pendingRun?.requestKey??crypto.randomUUID()}));
      setJobs(previous=>[job,...previous.filter(j=>j.id!==job.id)]);setJobRefresh(n=>n+1);setModal(null);setNotice('Job queued. You can leave this page; progress is saved.');
    }catch(e){setError(e instanceof Error?e.message:'Could not queue generation.');}
    finally{submission.current=false;setBusy(false);}
  }
  async function approve() {
    if (!campaign || !asset) return; setBusy(true); setError('');
    try { await jsonFetch(`/api/campaigns/${campaign.id}/approve`, postJson({ assetId: asset.id, generationId: generation?.id })); await load(campaign.id); setNotice(`${asset.name} approved.`); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function download(g: GenerationView | undefined) {
    if (!g?.imageUrl) return;
    try {
      const response = await fetch(g.imageUrl);
      if (!response.ok) throw new Error('Image download failed.');
      const blob = await response.blob();
      const extension = ({ 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/svg+xml': 'svg' } as Record<string,string>)[blob.type] || 'bin';
      const url = URL.createObjectURL(blob); const a = document.createElement('a');
      a.href = url; a.download = `${campaign?.name}-${asset?.kind}-v${g.version}.${extension}`; a.click();
      setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice('Asset downloaded.');
    } catch { setNotice('Image download failed. Check the server and try again.'); }
  }
  const combinedRuns = [...(campaign?.runs ?? [])];
  return <div className="app-shell">
    <aside className="sidebar"><Link className="brand" href="/" aria-label="CreativeFlow home"><span className="brand-mark"><Zap size={21} fill="currentColor"/></span><span>CreativeFlow<span className="ai-tag">AI</span></span></Link>
      <div className="workspace-switch"><span className="workspace-avatar">S</span><div>Studio workspace<small>Personal workspace</small></div><ChevronDown size={15}/></div>
      <div className="sidebar-label">WORKSPACE</div><button className={`nav-item ${!library ? 'selected' : ''}`} onClick={() => setLibrary(false)}><Layers size={18}/> Campaign studio</button><button className={`nav-item ${library ? 'selected' : ''}`} onClick={() => setLibrary(true)}><LayoutGrid size={18}/> All campaigns<span className="count">{campaigns.length}</span></button>
      <div className="sidebar-label campaign-label">CAMPAIGNS<button className="icon-button" aria-label="Create campaign" disabled={running} onClick={() => setModal('create')}><Plus size={15}/></button></div>
      <div className="campaign-list">{campaigns.map(c => <button key={c.id} className={`campaign-link ${campaign?.id === c.id ? 'active' : ''}`} onClick={() => openCampaign(c.id)}><span className="campaign-dot"/><span>{c.name}</span>{campaign?.id === c.id && <span className="tiny-dot"/>}</button>)}{!campaigns.length && !loading && <p className="small muted">Your campaigns will appear here.</p>}</div>
      <button className="new-campaign" disabled={running} onClick={() => setModal('create')}><Plus size={16}/> New campaign</button>
      <div className="sidebar-bottom"><div className="demo-card"><span><Sparkles size={15}/> Your creative sandbox</span><p>Explore mock mode without keys.<br/>Real providers may incur charges.</p><button className="text-button" onClick={() => setModal('settings')}>Provider settings <ArrowUpRight size={14}/></button></div><button className="nav-item" onClick={() => setModal('settings')}><Settings2 size={17}/> Settings & providers</button><div className="profile"><span className="profile-avatar">JD</span><div>Creative studio<small>Local workspace</small></div><CircleHelp size={17}/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span>/</span><button className="breadcrumb-button" onClick={() => setLibrary(true)}>Campaigns</button><span>/</span><strong>{campaign?.name || 'New campaign'}</strong></div><div className="topbar-right"><span className="mock-badge"><span/> {config.image === 'mock' ? 'Mock image mode' : config.image}</span><span className="avatar-small">JD</span></div></header>
      {error && <div className="error-banner" role="alert"><span>{error}</span><button onClick={async () => { setError(''); try { const list = await refreshList(); if (campaign) await load(campaign.id); else if (list[0]) await load(list[0].id); } catch (e) { setError((e as Error).message); } }}>Refresh</button><button aria-label="Dismiss error" onClick={() => setError('')}><X size={16}/></button></div>}
      {loading ? <div className="loading-state"><LoaderCircle className="spin"/><h2>Opening your studio…</h2></div> : library ? <main className="library"><div className="page-heading"><div><div className="eyebrow">YOUR CREATIVE WORK</div><h1>All campaigns</h1><p>From a single idea to a cohesive campaign.</p></div><button className="primary" disabled={running} onClick={() => setModal('create')}><Plus size={16}/> New campaign</button></div><div className="library-grid">{campaigns.map(c => <button className="library-card" key={c.id} onClick={() => openCampaign(c.id)}><span className="library-monogram">{c.brandName.slice(0, 1)}</span><small>{c.brandName}</small><h2>{c.name}</h2><div><span>{c._count.assets} assets</span><span className="tag">{c.status}</span></div></button>)}</div>{!campaigns.length && <p className="muted">Create your first campaign to begin.</p>}</main> : !campaign ? <main className="empty-workspace"><Sparkles size={38}/><h1>Your next great campaign starts here.</h1><p>Bring a brief. Build a direction. Create a consistent set of assets.</p><button className="primary" onClick={() => setModal('create')}><Plus size={16}/> Create your first campaign</button><small>For the seeded demo, run npm run setup.</small></main> : <>
        <section className="campaign-header"><div><div className="eyebrow"><span className="brand-initial">{campaign.brandName.slice(0, 1)}</span>{campaign.brandName.toUpperCase()}<span className="divider">/</span>CAMPAIGN</div><div className="title-row"><h1>{campaign.name}</h1><span className={`status-pill ${running ? 'working' : ''}`}><span/>{running ? 'In progress' : campaign.status === 'completed' ? 'Ready for review' : campaign.status}</span></div><p>{campaign.objective}</p><small>Creative Mode: {campaign.creative?modeDefinition(campaign.creative.mode).name:'Not recorded · historical campaign'}</small></div><div className="header-actions"><button disabled={running} onClick={()=>setModal('brand')}>Brand Intelligence</button><button onClick={() => setModal('brief')}><FileText size={15}/> View brief</button><button className="primary" disabled={!generation?.imageUrl || running} onClick={() => download(generation)}><Download size={15}/> Download asset</button></div></section>
        <JobStatus key={campaign.id} campaignId={campaign.id} refreshToken={jobRefresh} onJobs={setJobs} onCampaign={setCampaign}/><UsagePanel campaignId={campaign.id} title="Campaign usage" refreshToken={campaign.updatedAt}/><Workflow saved={generation?.context?.commercialPoster?{image:!!generation.imageUrl,vision:!!generation.evaluation}:undefined} runs={combinedRuns} running={running} onInspect={() => setModal('activity')}/>
        <div className="studio-toolbar"><div><button className="studio-tab active"><LayoutGrid size={15}/> Campaign assets <span>{campaign.assets.length}</span></button></div><div className="toolbar-meta"><span className="green-dot"/>{averageLabel}<span className="divider">|</span><span>{campaign.assets.filter(a => a.status === 'approved').length} approved</span></div></div>
        <main className="studio"><section className="assets-panel"><div className="section-label">ASSETS <span>{campaign.assets.length.toString().padStart(2, '0')}</span></div><div className="asset-list">{campaign.assets.map((a, i) => { const g = a.generations.at(-1); return <button key={a.id} onClick={() => { setSelected(a.id); setVersion(null); }} className={`asset-card ${asset?.id === a.id ? 'active' : ''}`}><div className={`asset-thumbnail ${a.kind}`}>{g?.imageUrl ? <img src={g.imageUrl} alt={`${a.name} composition`}/> : <ImageIcon size={26}/>}<span className="asset-number">0{i + 1}</span>{g?.evaluation && <span className="asset-score"><span/>{g.evaluation.overall} · {g.evaluation.provider === 'mock' ? 'Mock' : g.evaluation.provider === 'openai' ? 'Vision' : 'Unknown'}</span>}</div><div className="asset-card-title">{a.name}{a.status === 'approved' && <Check size={13}/>}</div><div className="asset-card-meta"><span>{a.width} × {a.height}</span><span>{a.status === 'approved' ? 'Approved' : g ? `v${g.version}` : a.status}</span></div></button>; })}</div></section>
        <section className="canvas-panel"><div className="canvas-top"><div><span className="canvas-icon"><ImageIcon size={17}/></span><div><h2>{asset?.name || 'Campaign canvas'}</h2><small>{asset ? `${asset.width} × ${asset.height} px` : 'Your assets will appear here'} <span>·</span> {generation ? `Version ${generation.version}` : 'Not generated'}</small></div></div><button className="icon-button" aria-label="Expand asset preview" disabled={!generation} onClick={() => setModal('preview')}><Maximize2 size={17}/></button></div>
          <div className="canvas-area">{generation?.imageUrl ? <div className={`image-frame ${asset?.kind}`}><img src={generation.imageUrl} alt={`${campaign.brandName}: ${asset?.name}, version ${generation.version}. campaign artwork.`}/><span className="preview-label">{generation.provider === 'mock' ? 'MOCK COMPOSITION' : 'GENERATED IMAGE'}</span></div> : <div className="canvas-empty"><Sparkles size={34}/><h2>{running ? 'Your creative team is at work' : generation ? 'Generation unavailable' : 'Bring your brief to life'}</h2><p>{running ? campaign.runs.at(-1)?.message || 'Follow the agent workflow above.' : generation?.context?.error || (campaign.creative?.mode==='commercial_poster'?'Create your campaign direction and one experimental Hero poster.':'Run the agents to create your campaign direction and coordinated assets.')}</p>{!running && <button className="primary" onClick={() => run(campaign.id)}><Sparkles size={16}/> Generate campaign</button>}</div>}</div>
          <div className="canvas-bottom"><div className="version-pills">{asset?.generations.map(g => <button key={g.id} className={generation?.id === g.id ? 'active' : ''} onClick={() => setVersion(g.version)}>V{g.version}<small>{g.evaluation?g.evaluation.overall+' · '+(g.evaluation.provider==='mock'?'Mock':g.evaluation.provider==='openai'?'Vision':'Unknown'):'No review'}</small><small>{reviewText(g.context?.workflowMode)||g.provider}</small>{g.id === latest?.id && <span>Latest</span>}</button>)}</div><button className="text-button" disabled={(asset?.generations.length || 0) < 2} onClick={() => setModal('compare')}><GitCompareArrows size={15}/> Compare versions</button></div>
          {generation&&<StopReason generation={generation}/>}
          {asset&&<UsagePanel campaignId={campaign.id} assetId={asset.id} title="Asset usage (all versions)"/>}{generation&&<UsagePanel campaignId={campaign.id} generationId={generation.id} title="Version usage"/>}{asset&&<RefinementTimeline asset={asset} selected={generation?.id} onSelect={setVersion}/>}
          <div className="asset-actions">{generation?.context?.commercialPoster&&!generation.evaluation&&<button disabled={running} onClick={()=>setModal('review-poster')}>Review poster with Vision</button>}<button disabled={running||asset?.kind!=='hero'||!campaign.uploads.some(u=>u.role==='product')} onClick={()=>setModal('commercial-poster')}>Commercial Poster — Klein v1 · Experimental</button><button disabled={running||!asset||!campaign.uploads.some(u=>u.role==='product')} onClick={()=>setModal('product-hero')}>Product Hero v1</button><button disabled={running||!generation?.imageUrl.startsWith('/api/generated/')} onClick={()=>setModal('repair')}>Repair region</button><div><button disabled={running || !latest} onClick={() => run(campaign.id, asset?.id)}><RotateCcw size={15}/> Regenerate</button><button disabled={running || !latest?.evaluation || !!generation?.context?.commercialPoster || !!generation?.context?.productHero} onClick={() => { setInstruction(''); setModal('refine'); }}><Sparkles size={15}/> Refine prompt</button></div><button className="approve-button" disabled={running || !latest?.evaluation || generation?.id !== latest?.id || asset?.status === 'approved' || !['ready', 'needs_review'].includes(asset?.status || '')} onClick={approve}><Check size={16}/>{asset?.status === 'approved' ? 'Approved' : 'Approve asset'}</button></div>
          {campaign.status === 'failed' && !running && !jobs.length && <button className="retry-button" onClick={() => run(campaign.id)}><RotateCcw size={15}/> Retry incomplete workflow</button>}
          <div className="canvas-footnote"><span className="green-dot"/>Human approval is the final step.<span>{generation?.provider || config.image} image · {visionLabel(generation?.evaluation)}</span></div>
        </section><Inspector campaign={campaign} generation={generation} threshold={config.threshold}/></main>
      </>}
    </div>
    {notice && <div className="toast" role="status"><Check size={17}/>{notice}</div>}
    {modal === 'create' && <CreateCampaign mockMode={config.image==='mock'} onClose={() => { setModal(null); refreshList().catch(() => {}); }} onCreated={async id => { setModal(null); setSelected(''); setLibrary(false); const created=await load(id); await refreshList(); if(created.uploads.some(u=>u.role!=='pose'))setModal('brand');else await run(id); }}/ >}
    {modal==='commercial-poster'&&campaign&&asset&&<Dialog title="Commercial Poster — Klein v1 · Experimental" onClose={()=>setModal(null)}><CommercialPosterPanel campaign={campaign} asset={asset} onQueued={()=>{setModal(null);setVersion(null);setJobRefresh(n=>n+1);setNotice('Commercial Poster queued. Vision review requires separate approval.');}}/></Dialog>}
    {modal==='review-poster'&&campaign&&generation&&<Dialog title="Review poster with Vision" onClose={()=>setModal(null)}><p>Send this poster, its original product reference, prompt and campaign strategy to OpenAI for one paid review. Estimated usage is recorded. No automatic refinement or image generation.</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await jsonFetch(`/api/campaigns/${campaign.id}/review-poster`,postJson({generationId:generation.id,confirmPaidReview:true}));await load(campaign.id);setModal(null);setNotice('Vision review saved. Inspect findings before approval.');}catch(e){setError((e as Error).message);setModal(null);}finally{setBusy(false);}}}>Run one paid review</button></Dialog>}
    {modal==='product-hero' &&campaign&&asset&&<Dialog title="Product Hero v1 · experimental" onClose={()=>setModal(null)}><ProductHeroPanel campaign={campaign} asset={asset} onQueued={()=>{setModal(null);setVersion(null);setJobRefresh(n=>n+1);setNotice('Product Hero queued. Previous versions are preserved.');}}/></Dialog>}
    {modal==='repair'&&campaign&&asset&&generation&&<Dialog title="Local repair" onClose={()=>setModal(null)}><RepairPanel key={generation.id} campaign={campaign} asset={asset} source={generation} onQueued={()=>{setModal(null);setVersion(null);setJobRefresh(n=>n+1);setNotice('Local repair queued. Source version is preserved.');}}/></Dialog>}
    {modal === 'readiness' && pendingRun && <Dialog title="Generation pre-flight" onClose={()=>setModal(null)}>{campaign?.creative&&runSelection&&<CreativeModeSelection value={runSelection} onChange={s=>setRunSelection({...runSelection,override:s.override})} references={campaign.uploads} placement={campaign.assets.find(a=>a.id===pendingRun.assetId)?.kind??'hero'} modeLocked/>}<ProviderReadiness workflowOverride={runSelection?.override??null} campaignId={pendingRun.id} assetId={pendingRun.assetId} refine={!!pendingRun.refine} conditioningStrength={conditioningStrength} onContinue={()=>executeRun(pendingRun.id,pendingRun.assetId,pendingRun.refine)}/></Dialog>}
    {modal === 'brand' && campaign && <Dialog title="Brand Intelligence" wide onClose={()=>setModal(null)}><BrandIntelligencePanel key={campaign.id} campaign={campaign} generationId={generation?.id} onUpdated={setCampaign}/></Dialog>}
    {modal === 'activity' && <Dialog title="Agent activity" onClose={() => setModal(null)}><div className="activity-list">{combinedRuns.length ? combinedRuns.map(r => <div key={r.id}><span className={`activity-dot ${r.status}`}/><div><h3>{r.stage}<span>{r.status}</span></h3><p>{r.message}</p><small>{new Date(r.createdAt).toLocaleTimeString()}</small></div></div>) : <p className="muted">Run your campaign to see each agent’s activity.</p>}</div></Dialog>}
    {modal === 'compare' && asset && campaign && <Dialog title="Compare versions" onClose={()=>setModal(null)} wide className="review-dialog"><VersionComparison key={asset.id} asset={asset} campaign={campaign} onInspect={v=>{setVersion(v);setModal(null);}}/></Dialog>}
    {modal === 'refine' && campaign && asset && <Dialog title="Refine the creative direction" onClose={() => setModal(null)}><form className="refine-form" onSubmit={e => { e.preventDefault(); run(campaign.id, asset.id, instruction); }}><p>Your feedback will guide a new prompt. Previous versions stay available.</p><label>What would you like to improve?<textarea autoFocus required minLength={3} maxLength={2000} rows={5} value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="e.g. More negative space, a softer reflection, and a tighter focus on the label."/></label><button className="primary"><Sparkles size={16}/> Refine & generate</button></form></Dialog>}
    {modal === 'brief' && campaign && <Dialog title="Campaign brief" onClose={() => setModal(null)}><div className="brief-view"><div className="eyebrow">{campaign.brandName}</div><h2>{campaign.name}</h2>{[['Objective', campaign.objective], ['Audience', campaign.audience], ['Creative brief', campaign.brief], ['Style', campaign.style]].map(([k, v]) => <div className="inspector-section" key={k}><h3>{k}</h3><p>{v}</p></div>)}<h3>Brand references</h3>{campaign.uploads.length ? <div className="reference-list">{campaign.uploads.map(f => <a key={f.id} href={`/api/uploads/${f.id}`} target="_blank" rel="noreferrer">{f.mime.startsWith('image/') ? <img src={`/api/uploads/${f.id}`} alt={f.name}/> : <FileText size={24}/>}<span>{f.name}<small>{f.role} · {(f.size / 1024).toFixed(0)} KB</small></span><ArrowUpRight size={14}/></a>)}</div> : <p className="muted">No reference files attached.</p>}<p className="mock-note">Product images guide product appearance; style references guide visual treatment; pose images guide body structure. Analyse logos and guidelines in Brand Intelligence, then review and approve the extracted rules.</p>{(['product','style'] as const).map(role=><div key={role}>{!campaign.uploads.some(f=>f.role===role || (role==='style' && f.role==='reference')) && <label className="upload-box">Add {role} reference<input type="file" accept="image/png,image/jpeg,image/webp" disabled={running} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append(role,file);await jsonFetch(`/api/campaigns/${campaign.id}/uploads`,{method:'POST',body:form});await load(campaign.id);setNotice('Reference saved.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label>}<label>{role==='product'?'Product':'Style'} influence for next run<input aria-label={role+' conditioning strength'} type="number" min="0.05" max={role==='product'?1.5:1} step="0.05" value={conditioningStrength[role]} disabled={running} onChange={e=>setConditioningStrength(s=>({...s,[role]:Number(e.target.value)}))}/></label></div>)}<p className="muted small">Influence values apply to the next run in this session. Past versions retain their recorded settings.</p>{!campaign.uploads.some(f=>f.role === 'pose') && <label className="upload-box">Add pose reference<input type="file" accept="image/png,image/jpeg,image/webp" disabled={running} onChange={async e=>{const file=e.target.files?.[0]; if(!file)return;setBusy(true);try{const form=new FormData();form.append('pose',file);await jsonFetch(`/api/campaigns/${campaign.id}/uploads`,{method:'POST',body:form});await load(campaign.id);setNotice('Pose reference saved.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label>}</div></Dialog>}
    {modal === 'settings' && <Dialog title="Providers & workspace" onClose={() => setModal(null)}><div className="settings-content"><WorkflowCatalog/><UsagePanel title="Workspace usage" expanded/>{campaign&&<UsagePanel campaignId={campaign.id} title="Current campaign usage"/>}<ProviderReadiness campaignId={campaign?.id}/><p>Provider choices are configured in your local <code>.env</code> file. Restart the server after a change.</p>{[['Language model', config.llm], ['Image generation', config.image], ['Vision critic', config.vision], ['Quality threshold', `${config.threshold}/100`], ['Max automatic refinements', String(config.max)]].map(([k, v]) => <div className="setting-row" key={k}><span>{k}</span><span className="tag">{v}</span></div>)}<div className="revision-note"><Sparkles size={20}/><p>Mock mode creates branded SVG layouts and deterministic critic scores. OpenAI structured text generation is available with your own API key. Local ComfyUI image generation is available with an installed checkpoint. OpenAI vision can inspect generated PNGs when VISION_PROVIDER=openai; mock reviews remain available.</p></div><p className="small muted">Local, single-user MVP. Your campaigns and references stay on this machine in default mock mode.</p></div></Dialog>}
    {modal === 'preview' && generation?.imageUrl && <Dialog title={`${asset?.name} · Version ${generation.version}`} onClose={() => setModal(null)} wide><div className="full-preview"><img src={generation.imageUrl} alt={`${asset?.name} expanded preview`}/></div></Dialog>}
  </div>;
}
